minor updates and useful options for the bst-duneuro
brainstorm-tools/brainstorm3 pull request #332
Opened 2020-09-17 20:44 UTC by tmedani

This mainly contains the following
- convert the format of the mesh element to uint64 (it's in this patch but it seems not required)
- add the possibility to check the source space when the keywords wm and gm are not used (we add the inner and scf key words)
- reduce the number of tests nFix  from 10 to 3, we will work in a better option soon, further is better, 
- add the possibility to save the real fem source space if it is different from the original as a checkbox from the duneuro panel, this can be useful for further investigation
- add the options cache.enable in the case of MEG, this is important since the MEG with high-density mesh and sensors require lot memory,  but this will slow the computation. Ideally, we may keep it for regular mesh and use it for high mesh density or when the MEG fails. This is also a checkbox option from the duneuro panel

2020-09-18 13:42 UTC, ftadel requested changes

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/bst_duneuro.m
> +FemMatx = FemMat;
All the file formats saved by out_fem are text-based.
I don't think converting to uint64 can make any difference.
Please revert this change.

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/bst_duneuro.m
> +        iGM = find(panel_duneuro('CheckType', FemMat.TissueLabels, 'inner'), 1);
Please pay attention to respecting the indentation of the code.
It's not difficult to do and it makes the code easier to read.
You can simply select the lines you edited in the file and press CTRL+I, Matlab will align the code correctly for you.

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/bst_duneuro.m
> +       if (iGM || iWM) == 0
iGM and iWM are values that can be empty, therefore this test can crash.
You should test this with:
`if isempty(iGM) && isempty(iWM)`

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/bst_duneuro.m
> +       if (iGM || iWM) == 0
Same: invalid test.

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/bst_duneuro.m
> +            NewTess = db_template('surfacemat');
Indentation

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/panel_duneuro.m
> +        jCheckSaveTransfer = gui_component('checkbox', jPanelOutput, 'br', 'Save transfer matrix', [], '', [], []);
'br' is for moving to the next line.
This is the first line: not needed here.

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/panel_duneuro.m
> +            jCheckMegCacheEnable = gui_component('checkbox', jPanelOutput, 'br', 'Enable cache memory', [], '', [], []);
Is this really an "output option"?
I don't know at which level it impacts the computation, but it might require a new panel "Computation options"?

2020-09-18 13:42 UTC, ftadel commented on toolbox/forward/panel_duneuro.m
> +        jCheckSaveSourceSpace = gui_component('checkbox', jPanelOutput, 'br', 'Save source space', [], '', [], []);
This could make more sense in the panel "Source space", right?
And maybe be disabled if both "Shrink source space" and "Force source space inside brain" are disabled?
(I can make this last thing for you if you validate the logic)

2020-10-01 16:23 UTC, tmedani commented
Hi @ftadel , 
sorry for my low reaction, 
I'm working on it, and some other improvements, 
I will push all the changes asap.

2020-10-12 22:18 UTC, closed without merging