Improve the bst-iso2mesh version for fem mesh and add new option to refine the fem mesh
brainstorm-tools/brainstorm3 pull request #341
Opened 2020-10-15 02:07 UTC by tmedani

This first version of this PR is related to the FEM mesh generation with **iso2mesh** option and the mesh refinement,
 
1- Remove most of the previous version and implement a new version, which I think is more stable
=> possibility to generate mesh from any merged surfaces with non-predifined names and the labels will be identified
=> All the unknown element labels from surf2mesh are identified by computing the distance to the center of the brain and then check with the input surfaces ID.
This can be useful in the case of high mesh densities, and  where only the inner layers are required, 
for example, wm, gm and csf for sEEG

2- Add a new option to re-fine a specific area of the FEM mesh (new function by the right click on the FEM mesh => Refine FEM mesh)
=>The refinement or the adaptative mesh area can be defined by a set of 3D points where the mesh can be refined, by dividing the mean edge length by a factor that the user can change. 
I have added the following options, that I think are useful : 
-a- areas surrounding the cortex,
-b- area surrounding the position of the electrodes (eeg/ecog and seeg)  
-c- both a and b 
-d- load any 3D points from file or Matlab (TODO)

The following example shows a case where the refined area is around the cortex surface. 
![image](https://user-images.githubusercontent.com/37831900/96067075-c5e01600-0e4d-11eb-869f-916ccf6beacc.png)

and this one around an sEEG electrodes
![image](https://user-images.githubusercontent.com/37831900/96068074-f2952d00-0e4f-11eb-95ab-b388af6d7aa6.png)

@ftadel the code is working correctly however it's not clean, 
I left some commented codes that I'm using for visualization and testing. 
If you agreed with this new version and its results I can clean it, and improve it.
And also optimize the code since either the refinement and the fem mesh generation uses ~the same process.

2020-10-24 16:22 UTC, ftadel requested changes

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +                k = dsearchn(nodeList,[maxYpoint;minYpoint]);
If you need this to be fast, in some configurations bst_nearest can be much faster.

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +            %  Sort from inner to outer
I thought that the detection of the layer type based on the distance was NOT working? 
Is it something very different that you did here, than the version that we deleted before?

What was wrong with the idea of identifying the layers with their labels? (which you delete here)

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +                OPTIONS.KeepRatio, factor_bst .* OPTIONS.MaxVol, (regions), [], [], 'tetgen1.5');
What is the point of adding parenthesis to "(regions)" ?

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +                OPTIONS.KeepRatio, factor_bst .* OPTIONS.MaxVol, (regions), [], [], 'tetgen1.5');
Since the variable regions is not used anywhere else, use directly listPointasSeed instead.

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +             allLabels = unique(tmp(:,5));
Please fix indentation

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +            tmp(:,5) = tmp(:,5) +10; % translation to avoind overlapping
avoid

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +            tmp = elem;
Variable is not used between `tmp = elem;` and `elem = tmp;`
Just work directly on `elem`.
Less variables = higher readability.

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +%% ===== Refine Mesh =====
This is a completely independent process, and should be handled as such.
Ideally we would like to be able to call from a script as well.
=> Create a new process_fem_refine.m

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +    % sort weired elements, works in all case even when there are
There is a lot of copy-paste between this function and the iso2mesh mesh generation.
Could try factorizing a bit the code? 
(= add a new function, either stand-alone fem_...m if it makes sense, or included in process_fem_mesh otherwise)

2020-10-24 16:22 UTC, ftadel commented on toolbox/tree/tree_callbacks.m
> +                    gui_component('MenuItem', jPopup, [], 'Refine FEM mesh', IconLoader.ICON_FEM, [], @(h,ev)bst_call(@process_fem_mesh, 'RefineMesh', filenameRelative));
Call process_fem_refine('Compute', ...) instead

2020-10-24 16:22 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +%% ===== Refine Mesh =====
When moving this to a new process: 
Separate this whole thing in two functions: Compute and ComputeInteractive, as in many other processes, in order to have both an interactive and a command line call.

2020-10-26 23:41 UTC, tmedani commented on toolbox/process/functions/process_fem_mesh.m
> +                k = dsearchn(nodeList,[maxYpoint;minYpoint]);
ok, I don't know this function. 
I will check it. Thanks

2020-10-26 23:57 UTC, tmedani commented on toolbox/process/functions/process_fem_mesh.m
> +            %  Sort from inner to outer
>> I thought that the detection of the layer type based on the distance was NOT working?
I'm using another approach, where I use the triangular mesh as a reference for the distances,
which is not used before. 

>>Is it something very different that you did here, than the version that we deleted before?

Yes, this is totally different, I think this method is more "robust" it can define the unknown labels (outputs of surf2mesh), and also reorder them according to the reference distances.
 

>>Is it something very different that you did here, than the version that we deleted before?

in most case, this error appears if we use different surfaces than (inner, outer and scalp) 
 errMsg = ['Problem with Tetget: Brainstorm cannot understand the output labels (' num2str(allLabels(:)') ').'];

and if the output labels from surf2mesh are different from [1 2 3] the process stops, even if the tetgen works fine.

for example, here is the error if I use white, csf, and grey 👍 
![image](https://user-images.githubusercontent.com/37831900/97240427-7d105180-17ab-11eb-82c1-7a1a6d91f1e2.png)

but with the new method, this is working, even if the outputs labeled (1 2 3 4) are weird
![image](https://user-images.githubusercontent.com/37831900/97240738-50106e80-17ac-11eb-8d08-1ad84459f39a.png)

2020-10-31 13:30 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +            %  Sort from inner to outer
> but with the new method, this is working, even if the outputs labeled (1 2 3 4) are weird

But they are not labelled correctly, and the predefined colors are incorrect?
Why not keep the identification by name AND use your new code when the layers do not have standard names?

The standard case will be that people will use fully automated pipelines, like simnibs or brain2mesh, which will produce layers that we can clearly identify. Why not benefit from this?
The case where people mix and match surfaces like you do will be very marginal.

2020-11-25 01:19 UTC, tmedani commented
This PR needs more work and changes. 

I will close it, and create a new PR asap.

2020-11-25 01:19 UTC, closed without merging