Enhance the LF viewer and adding more options from the keyboard
brainstorm-tools/brainstorm3 pull request #343
Opened 2020-10-16 00:59 UTC by tmedani

Hi @ftadel, 

This PR is to complete the PR that @juangpc proposed (https://github.com/brainstorm-tools/brainstorm3/pull/337#issue-496360490), and it includes also the proposed option.

It includes useful options to visualize and manipulate the LF vectors, all these options are managed from keyboard shortcuts, they can be displayed with the 'H' keyboard key, as in this figure : 

![image](https://user-images.githubusercontent.com/37831900/96200338-80cfe880-0f0e-11eb-90e9-4a5750fca877.png)

With this version, the average reference option can be also selected from the same list as the channels (R) instead to have multiple popup panels, the "target channels (T) can be also selected from a dedicated list, which is useful in the case where users want to see the LF between two specific channels. 

There are also functions that change the scale, the length, and the width of the vectors. Furthermore, there is a way to threshold the displayed vectors by fixing the Amplitude threshold as shown in the figure. All this interactively with the figure & the keyboard (as usual with Branstom figure 👍  ).

For the standard view keyboard (1-9), I have used the same subfunctions "SetStandardView" that I have copy-pasted to this function. 

All these options are for visualization purposes, the next dev should focus on functions that can 
quantitatively compare these differents LF models. 

Also, the idea behind these new options is not only for the LF, but also to extend the use for the optical flow (https://github.com/brainstorm-tools/brainstorm3/pull/311), as previously discussed with @LeoNouvelle  @martcous & @sbaillet

I hope this will be useful :)

A+
Takfarinas

2020-10-24 16:42 UTC, ftadel requested changes

2020-10-24 16:42 UTC, ftadel commented on toolbox/gui/view_leadfields.m
> +iQuiverSize = 1;
The convention in the rest of the code is "iVariableName" being an index. 
https://neuroimage.usc.edu/brainstorm/Tutorials/Scripting#Naming_conventions

These are not indices.
Can you please rename the variables?

2020-10-24 16:42 UTC, ftadel commented on toolbox/gui/view_leadfields.m
> +                    '<TR><TD><B>Shift + L</B></TD><TD>Toggle on/off logarithmic scale</TD></TR>'...
Looks like this is "Shift + Enter" instead

2020-10-24 16:42 UTC, ftadel commented on toolbox/gui/view_leadfields.m
> +            case '0'
Delegate all this to figure_3d instead.
In the otherwise block, it should call figure_3d/FigureKeyPressedCallback and set the orientation.
Or am I missing something?

2020-10-24 16:42 UTC, ftadel commented on toolbox/gui/view_leadfields.m
> +    function lf_log = logScaledLeadField(lf)
As this is a function, it would be better if it were named as an action.
For example: ScaleLeadfield

But since this is called only once and not very long, I suggest you integrate it directly into where it is required.
(and not keep it as a separate function)

2020-10-24 16:42 UTC, ftadel commented on toolbox/gui/view_leadfields.m
> +    function SetStandardView(hFig, viewNames)
I don't understand why you copy-pasted a function from figure_3d here.
If you need to call a function in a different file, use the syntax figure_3d('FunctionName', param1, param2...)

2020-10-25 21:13 UTC, tmedani commented on toolbox/gui/view_leadfields.m
> +iQuiverSize = 1;
ok I will correct it,

2020-10-25 21:16 UTC, tmedani commented on toolbox/gui/view_leadfields.m
> +                    '<TR><TD><B>Shift + L</B></TD><TD>Toggle on/off logarithmic scale</TD></TR>'...
I think both are working, 
"Shift + Enter" and "Shift + L"

2020-10-25 21:18 UTC, tmedani commented on toolbox/gui/view_leadfields.m
> +            case '0'
You're right, 
I did not manage to link the current function  with the figure_3d

2020-10-25 21:19 UTC, tmedani commented on toolbox/gui/view_leadfields.m
> +    function lf_log = logScaledLeadField(lf)
ok, I will correct it

2020-10-26 11:32 UTC, ftadel commented on toolbox/gui/view_leadfields.m
> +            case '0'
The block `otherwise` in the switch calls `KeyPressFcn_bak(hQuiver, keyEvent)`, which actually calls the original handler from figure_3d (`figure_3d/FigureKeyPressedCallback`). You don't have to do add anything so that figure_3d processes the orientation keys. 
If you have any trouble, add a breakpoint at the beginning of `figure_3d/FigureKeyPressedCallback` to check what is wrong.

In general, if you need to call a function in a different file, use the syntax `figure_3d('FunctionName', param1, param2...)`

2020-10-26 14:48 UTC, juangpc commented on toolbox/gui/view_leadfields.m
> +    function lf_log = logScaledLeadField(lf)
Hi, This is just an open comment. Please don't modify your intentions. 
- the integration of the scaling function in the main flow. I personally wouldn't integrate it. Keeping simple, atomic, operations in a codebase, abstracted of everything else, as much as possible, I think makes the code easier to follow, debug and, eventually, reuse code, etc... This might be a bad example because of its simplicity, but still. 
- Totally agree with the renaming. Would suggest LogScaleLeadfield, but ScaleLeadfield is just fine.
Thanks for reading.

2020-10-26 16:04 UTC, tmedani commented on toolbox/gui/view_leadfields.m
> +    function SetStandardView(hFig, viewNames)
I did not manage to use figure_3d in this function, but if you think it's possible I will try to do it.

2020-10-26 20:29 UTC, tmedani commented on toolbox/gui/view_leadfields.m
> +    function lf_log = logScaledLeadField(lf)
Hi, I have corrected the PR according to the discussion, and regarding this comment I changed only the name of the sub-function "ScaleLeadfield", I think also it's more convenient to have as a subfunction, but this is also my comment.
so, @ftadel if you don't like it I will change it :)

2020-10-26 20:30 UTC, tmedani commented on toolbox/gui/view_leadfields.m
> +            case '0'
Ok, I got it, the problem was in the figure handles, 
![image](https://user-images.githubusercontent.com/37831900/97225109-6cea7900-178f-11eb-9755-1f5203191077.png)

Now it's working. 

Thanks :)

2020-10-31 12:40 UTC, merged