Prevent Y log scale with negative data
brainstorm-tools/brainstorm3 pull request #348
Opened 2020-10-22 01:36 UTC by Moo-Marc

Avoid errors when trying to apply y axis log scale on log-power data.  

Strangely, the y scale log option in the "display configuration" button on psd figures activates the function SetScaleModeY in figure_timeseries, while in the right-click menu, it activates the function ToggleLogScaleY in figure_spectrum.  That confused me for a while.

2020-10-22 21:42 UTC, Moo-Marc commented
I think I ironed out most kinks.  I only tested with PSD plots.  I'm not sure if these changes would affect time-freq plots?

2020-10-24 11:10 UTC, ftadel requested changes

2020-10-24 11:10 UTC, ftadel commented on toolbox/gui/figure_timeseries.m
> +    [hFig, iFig, iDS] = bst_figures('GetFigure', hFig);
Use the accessor `Handles = bst_figures('GetFigureHandles', hFig);` instead

2020-10-24 11:24 UTC, ftadel commented
> the y scale log option in the "display configuration" button on psd figures activates the function SetScaleModeY in figure_timeseries, while in the right-click menu, it activates the function ToggleLogScaleY in figure_spectrum

Indeed, this is not optimal to have two ways of handling this. Maybe replacing the Xlog and Ylog checkboxes for the display menu of the spectrum figures with two radio buttons (Linear/Log) as in the popup menu would be easier to read. And it would allow to call only one function (SetScaleModeY) and remove the other one (ToggleLogScaleY).
If the handling of X and Y axis is similar in terms of code, it would be better.
Feel free to propose something simpler. 

> I'm not sure if these changes would affect time-freq plots?

There are no reference to these functions in figure_timefreq, so it won't affect the TF plots.
However, the timefreq files (Hilbert, Morlet, coherence, spectral Granger, PLV, ...) can be displayed as spectrum figures, you should check that all this still works as expected.

2020-10-26 17:23 UTC, Moo-Marc commented on toolbox/gui/figure_spectrum.m
> +    if ~isfield(TsInfo, 'XScale')
These tests were already there, just a little lower.  I just tested and apparently they're not needed, so agreed.

2020-10-26 17:57 UTC, Moo-Marc commented
> And it would allow to call only one function (SetScaleModeY) and remove the other one (ToggleLogScaleY)

It was simple to just reuse SetScaleModeY in both cases, but I'll keep the gui as is for now.  I personally prefer the checkmark in the display menu.  The pop-up menu "Y scale: log" is a bit ambiguous as to whether it shows the current setting or if it means "Set Y scale to: log".  But that menu has icons where the checkmark would go.

2020-10-27 02:48 UTC, Moo-Marc commented
Tested TF-linked spectrum figure.  Works fine.
There's still an issue with FOOOF spectra (probably to do with their NaNs), but there will be another PR for that and other fooofy stuff soon.

2020-10-29 03:22 UTC, Moo-Marc commented
Last commit before updating the tutorial screenshots. 
Display the real units in spectrum, e.g. fT for MEG.
Plus fixed a bug on TF-linked timeseries figure (auto scale y didn't work).

2020-10-30 15:25 UTC, Moo-Marc commented
Updated tutorial screenshots and What's New.

2020-10-31 13:52 UTC, merged