Integration of NIRSTORM in Brainstorm plugin system
brainstorm-tools/brainstorm3 pull request #401
Opened 2021-04-08 17:43 UTC by Edouard2laire

2021-04-08 18:24 UTC, Edouard2laire commented
EDIT: wait before mergig this :)

2021-04-08 18:34 UTC, Edouard2laire commented
ok. should be good now. Before NIRSTORM was not properly uninstalled at the first lunch of brainstorm.

2021-04-12 09:09 UTC, ftadel requested changes
Looks good!
Just a few details to fix.

2021-04-12 09:09 UTC, ftadel commented on toolbox/core/bst_startup.m
> +            cur_dir=pwd;
`1) Shouldn't `uninstall_nirstorm` be executed before deleting `OldPlugPath`?

2) Please move the folder change inside the test for `nirstorm`: no need to switch folder for the other plugins.

2021-04-12 09:09 UTC, ftadel commented on toolbox/core/bst_plugin.m
> +    PlugDesc(end).TestFile      = 'nst_install.m';
Do you still need `nst_install.m`?
Otherwise, maybe it's not a good `TestFile`.

2021-04-12 09:09 UTC, ftadel commented on toolbox/core/bst_plugin.m
> +                URLzip = 'https://github.com/Nirstorm/nirstorm/archive/master.zip';
You can remove this line, as the URL does not depend on the version.

2021-04-12 13:32 UTC, Edouard2laire commented on toolbox/core/bst_startup.m
> +            cur_dir=pwd;
1. it doesn't matter. uninstall_nirstorm is deleting the file in the .process folder 
2. Done

2021-04-12 13:32 UTC, Edouard2laire commented on toolbox/core/bst_plugin.m
> +    PlugDesc(end).TestFile      = 'nst_install.m';
Done

2021-04-12 13:32 UTC, Edouard2laire commented on toolbox/core/bst_plugin.m
> +                URLzip = 'https://github.com/Nirstorm/nirstorm/archive/master.zip';
Done

2021-04-14 08:04 UTC, merged

2021-04-14 08:20 UTC, ftadel commented
I could not test the uninstall, as I already had removed it. 
But the new installer works well. Thanks!

I just removed the \n at the end of the version string, which was causing the install/update dialog boxes to display in a very ugly way.
https://github.com/brainstorm-tools/brainstorm3/commit/2281ba0545276c6d42242d9780bd75e9f67acb45#diff-dc8f8ced87ae44db6a025ad870e6b46c1c6569c2a857ae2003e2be9ba2ff0599R432