improved/robust version for the iso2mesh option within process_fem_mesh
brainstorm-tools/brainstorm3 pull request #422
Opened 2021-07-03 03:48 UTC by tmedani

Hi all,

This PR is about the issue observed when the iso2mesh option is used, and surf2mesh produces more element labels than the input surfaces.
link to the reported issue: https://neuroimage.usc.edu/forums/t/duneuro-error-calculation/28965/6?u=tmedani

The change on this code will identify any output label based on the distance comparison between the inputs surfaces and the outputs labels.
I believe that is much robust than the previous version.

This change can be also useful for custom fem mesh generation for sEEG/iEEG models.

Thanks :)

2021-07-09 10:54 UTC, ftadel requested changes
Since this is probably still an algorithm that we'll need to refine, I made it a new option `iso2mesh-2021` instead of editing the existing code.

There are some new issues to fix with the labeling of the different layers.

2021-07-09 10:54 UTC, ftadel commented on toolbox/process/functions/process_fem_mesh.m
> +                % Get tissue label
Here you removed the sorting and relabelling of the labels based on their names.
In some of the tests I made, the tissues ended up being incorrectly labelled in the FEM file...

For example, with the labels from MNE: `outer_skin.surf`, `outer_skull.surf`, `inner_skull.surf`
In the output FEM file, the layers don't get renamed in `scalp`, `skull`, `csf`, and they get incorrectly colored in the display.

Before:
![image](https://user-images.githubusercontent.com/6920058/125067433-8f6db980-e0b4-11eb-9a4e-71da0d83a225.png)

After:
![image](https://user-images.githubusercontent.com/6920058/125067449-94326d80-e0b4-11eb-9b06-81f295f3d4a5.png)

2021-07-09 16:40 UTC, tmedani commented
Hi Francois, 
Thanks for reviewing  this, 
I think having both options is better (iso2mesh and iso2mesh2021),
if the first fails, one can tests the second. 

Regarding the issue that you highlighted, I will check it.

2021-07-15 21:59 UTC, closed without merging

2021-07-15 22:12 UTC, tmedani commented
Hi Francois, 

by a bad command line, I removed the change of the of this PR, 
by any chance do you still have the changes that you proposed for iso2mesh2021 version locally?

2021-07-16 15:49 UTC, ftadel commented
No, I deleted the branch on my computer.
It sucks, there were quite a lot of edits in there...

When you want to work on a particular feature to merge with the master Brainstorm branch, create a separate branch on your own git local repository, instead of working only from your master branch. One branch per feature.
This way, simultaneous work on different features won't interfere with the reviewing process of individual PRs.

Example: We're working with Raymundo on the support for a new file format, he created a new branch, pushed it, we reviewed and edited it together, opened a PR for it (https://github.com/brainstorm-tools/brainstorm3/pull/416), and now he can keep on working on other things in different branches while this goes through the reviewing process.

Good luck with rewriting everything...

2021-07-16 22:15 UTC, tmedani commented
Thanks, Francois, I used to work with branches before but not at this time. 
I believe that I can reproduce the code.
I will push a new PR next week.