First commit, coherence-2021
brainstorm-tools/brainstorm3 pull request #423
Opened 2021-07-06 00:54 UTC by rcassani

This is the first draft towards the coherence-2021 update. 
It shows that the Input data X and Y are cell arrays, where each cell is a 2D array `[nSignals, nSamples]`.
For the moment the case N×N MSC is shown in `bst_cohn_2021.m`. Additional cases will be added in next commits.
An additional function `bst_epoching.m` is added for convenience. Its current path may not be the ideal.

2021-07-07 15:50 UTC, ftadel requested changes
I added the wrappers you needed to call your new function bst_cohn_2021.m from the interface.  I created a new set of process functions and deprecated the previous ones.
I hope it's not too buggy...

Could you write a simple script, based on simulated data, that allows computing exactly the same thing with the older and the new processes? 
(it could be the Test functions of the process_cohere1* functions for instance).
This would help for comparing the execution speed of the two versions, in order to optimize our implementation choices as we go.

I review the bst_cohn_2021 function in more details when you are more advanced with the integration of the other options (or whenever you need - just ask)

2021-07-07 15:50 UTC, ftadel commented on toolbox/connectivity/bst_cohn_2021.m
> +    nMinMessage = nWinLen * (1 - nOverlap) * (minWinError - 1);
This produces error messages that do not make sense. 
nMinMessage computation must be reviewed.

2021-07-07 15:50 UTC, ftadel commented on toolbox/connectivity/bst_cohn_2021.m
> +    epy = bst_epoching(y, nWinLen, nOverlap);
I'm not convinced by the necessity to have a separate subfunction.
bst_epoching does more than what we need here (2 of the 3 outputs are not used).
If written in a compact way, it would be only a few lines of code added here.

Since it duplicates the input data, it might also pack the memory unnecessarily.
Have you tested how much it decreases the execution speed, to have the ftt called in this vectorized format instead of in a for loop on the epochs?

If for clarity you want to have separate function, or if this helps you factoring code in when you add the other cases, maybe this could be moved to a local subfunction. I guess it won't be used much outside of this function.

2021-07-07 16:38 UTC, rcassani commented on toolbox/connectivity/bst_cohn_2021.m
> +    epy = bst_epoching(y, nWinLen, nOverlap);
It does a bit more. I thought it could come handy whenever we need to epoch data and keep a reference to when the epochs are places `time_vector(ixs_ctr)`.

Yes, the vectorization of FFT helps, it's between 2 and 5 times faster. It also adds clarity. See this gist:  https://gist.github.com/rcassani/ca12d325c82997988e6313e1454da385

2021-07-07 23:01 UTC, rcassani commented on toolbox/connectivity/bst_cohn_2021.m
> +    nMinMessage = nWinLen * (1 - nOverlap) * (minWinError - 1);
Fixed in 668c1e7c1e84975a45d58572458d1bd2b05e970c

2021-07-07 23:05 UTC, rcassani commented
Find the comparison/test for `bst_cohn.m` and `bst_cohn_2021.m` here: 
https://gist.github.com/rcassani/ca12d325c82997988e6313e1454da385#file-fft_vectorized_test-m

2021-07-08 06:44 UTC, ftadel commented
> Find the comparison/test for bst_cohn.m and bst_cohn_2021.m here

Great, thanks.
Could you please include these test functions in one of the coherence process?
Or anywhere else in the actual brainstorm code repository, for future reference?

2021-07-09 15:58 UTC, rcassani commented
> Could you please include these test functions in one of the coherence process?  

Comparison included in `process_cohere1n_2021('Test')` in 34730dff9e4930594894acd0784a0d5bfb339f1b

Regarding the epoching function, I think we can use it in the future to vectorize some other processes that are window-wise are are written as loops.

2021-07-12 20:08 UTC, rcassani commented
@ftadel, 
- The epoching function was moved inside `bst_cohn_2021.m`
- Test functions added where pertinent

2021-07-14 14:20 UTC, ftadel commented
Do you think this is ready to be merged?

2021-07-14 19:24 UTC, rcassani commented
@ftadel 
It's ready to merge.
P.S. There is a commented section to compute `Sxy` in a vectorized way, it's much faster but it takes a good amount of RAM.

2021-07-16 17:19 UTC, merged

2021-07-16 17:25 UTC, ftadel commented
I moved back the old process functions from the deprecated folder to the regular process folder.
Since the results we obtain can look pretty different with the two processes, this will make it easier to compare the old and new values.
I hope this OK with you?

Could you document this update somewhere in the tutorials, so we could point at some online documentation (eg. the `Description` field of the process functions)?
Thanks!

2021-07-19 12:25 UTC, rcassani commented
Sounds good. The changes will be documented in the connectivity tutorials.