Bids nirs
brainstorm-tools/brainstorm3 pull request #470
Opened 2021-12-06 17:16 UTC by Edouard2laire

First implementation of BIDS for NIRS. (fix #469)

This is almost ready. I am only strugling to read the coordinate of the optodes. We need to read '*_coordsystem
.json' and '*_optodes.tsv'

corrdsystem looks like: 
```
{
    "NIRSCoordinateSystem": "CapTrak",
    "NIRSCoordinateSystemDescription": "The X-axis goes from the left preauricular point (LPA) through the right preauricular point (RPA). The Y-axis goes orthogonally to the X-axis through the nasion (NAS). The Z-axis goes orthogonally to the XY-plane through the vertex of the head. This corresponds to a \"RAS\" orientation with the origin of the coordinate system approximately between the ears. See Appendix VIII in the BIDS specification.",
    "NIRSCoordinateUnits": "m"
}
```
and optodes looks like 
```
﻿name	type	x	y	z
S1	source	-0.041613204679326624	0.026799775287857947	0.1299043936308115
D1	detector	-0.037619588707178915	0.06322851630256272	0.11572802770110814
```

What i think need to be modified: 
-  https://github.com/Edouard2laire/brainstorm3/blob/BIDS-nirs/toolbox/process/functions/process_import_bids.m#L597 : currently electrodesSpace is UNKNOWN; guess should be either ORIG or MNI
- Modify process_channel_addloc to work with nirs. optodes.tsv contains the coordinate of all sensors; strucutre in matlab contains the channels (combination of a source and detector). So when reading for exemple coordinate of S1 we need to modify the coordinate of all channels containing S1. 

Regards, 
Edouard

2021-12-06 18:03 UTC, ftadel commented
> edit: actually i don't understand the subfunction SelectCoordSystem

It selects which _electrode.tsv (or _optode.tsv) should be read as the coordinates for the Brainstorm channel files.
Only "MNI" and "Other" (related to the associate MRI) are supported.
By order of preference: Other (subject space), and if not available MNI (requires a non-linear normalization procedure).

As in this example: https://github.com/bids-standard/bids-examples/tree/master/ieeg_epilepsy_ecog/sub-ecog01/ses-postimp/ieeg

How do you expect to be able to convert from the coordinates in these files into Brainstorm SCS coordinates?
Is it at all possible?

2021-12-06 18:35 UTC, Edouard2laire commented
I guess it's possible: the coordinate are also saved in the .snirf file along with the fiducials coordinate and when read fron there it's aligned with the anatomy : https://github.com/brainstorm-tools/brainstorm3/blob/d5a0885e92b54c89cce65e5306d5813b56d4969c/toolbox/io/in_data_snirf.m#L83-L111


We need to have similar code but reading from the otpodes file i guess.

2021-12-24 11:42 UTC, ftadel requested changes

2021-12-24 11:42 UTC, ftadel commented on toolbox/io/in_data_snirf.m
> +switch strtrim(str_remove_spec_chars(jnirs.nirs.metaDataTags.LengthUnit{:}'))
This can't work: there is only one parameter in input to `str_remove_spec_chars`, and this syntax `{:}` would call the function with multiple parameters if there are multiple values.
Plus, using `switch` with multiple values won't work.

If `LengthUnit` is a cell array with one string only, you can use `{1}` instead.

2021-12-24 11:42 UTC, ftadel commented on toolbox/io/in_data_snirf.m
> +    DataMat.Events(iEvt).label      = strtrim(str_remove_spec_chars(jnirs.nirs.stim(iEvt).name{:}));
Same comment as before.
In `.label`, you want have only one string, not multiple values.
Therefore you might want to use `{1}` instead of `{:}`.

2021-12-24 11:42 UTC, ftadel commented on toolbox/io/in_tsv.m
> +if tsvHeader{1}(1) == char(65279) % WEIRD
What is this?

(double problem: it conflicts with the recent edits I made to in_tsv.m)

2021-12-24 11:42 UTC, ftadel commented on toolbox/process/functions/process_import_bids.m
> +                        if isfield(sCoordsystem, 'NIRSCoordinateUnits') && ~isempty(sCoordsystem.NIRSCoordinateUnits) && ismember(sCoordsystem.NIRSCoordinateUnits, {'mm','cm','m'})
Combine this with the previous test with and `elseif`.
It's either one OR the other.

2021-12-24 11:43 UTC, ftadel commented
(sorry for the delay...)

2021-12-24 11:51 UTC, Edouard2laire commented
Thanks a lot for the comments. However I won’t have time to have a look before January. 

Happy Christmas :)

2022-06-08 10:47 UTC, ftadel commented
Any update?

2022-06-08 14:11 UTC, Edouard2laire commented
Sorry, i totally forgot about it. i will try to come back to it later this week. I am still not very sure about how to deal with the coordinate system.

2022-07-04 17:36 UTC, Edouard2laire commented
closing the PR for now. Will reopen when I have time to work on it

2022-07-04 17:36 UTC, closed without merging