Spectral Parameterization Resolved in Time (SPRiNT)
brainstorm-tools/brainstorm3 pull request #484
Opened 2022-01-22 01:12 UTC by lucwilson

The Spectral Parameterization Resolved iN Time (SPRiNT) algorithm is designed to identify and model spectral features of the neural activity across time. Beginning with the time-series, it performs a short-time Fourier transform (STFT) and averages windows locally in time to generate local-mean power spectra, before decomposing these spectra into aperiodic and periodic components using _specparam_.

A tutorial has already been developed using the tutorial dataset and can be found at https://neuroimage.usc.edu/brainstorm/Tutorials/SPRiNT.

Includes visualization tools, leveraging features for specparam/FOOOF data structures already present in Brainstorm.

This also updates the gui to read 'specparam' everywhere it previously read 'FOOOF' (mostly panel_display). This does not modify output data fields (though perhaps a transition from 'FOOOF' to 'specparam' is in the cards down the road). 

Please let me know if there are any issues or inconsistencies in the code!

2022-01-22 08:58 UTC, ftadel requested changes
Thank you for this new valuable contribution!

2022-01-22 08:58 UTC, ftadel commented on toolbox/core/bst_memory.m
> +            TimefreqMat = in_bst_timefreq(TimefreqFile, 0, 'TF', 'TFmask', 'Time', 'Freqs', 'DataFile', 'DataType', 'Comment', 'TimeBands', 'RowNames', 'RefRowNames', 'Measure', 'Method', 'Options',
This reads twice the file, and should be avoided.
I think you can remove this test on `Method` and directly add the `'SPRiNT'` field in the call to `in_bst_timefreq` above: if the field is missing in the file, then it will return an empty matrix for it. 
This is already what is done for other extra fields added with previous hacks (e.g. 'sPAC') 

(Read and answer the comment about the differences between FOOOF and SPRiNT before adressing this one)

2022-01-22 08:58 UTC, ftadel commented on toolbox/core/bst_memory.m
> +        isSPRiNT = isfield(GlobalData.DataSet(iDS).Timefreq(iTimefreq), 'SPRiNT') && ~isempty(GlobalData.DataSet(iDS).Timefreq(iTimefreq).SPRiNT);
**READ FIRST** (as it may invalidate many other comments)
--

Why did you decide to add `SPRiNT` directly in the `Timefreq` structure, instead of the `Options` struct, like the `FOOOF` structure?
That would avoid modifying all the other files and make the two implementations easier to compare side-by-side.  
The closer the two data structures, the easier the future maintenance.

If you decided on this solution to correct a previous choice that you regret, then adding a different type of storage solution now is not necessarily the best solution. These basic data structures were not meant initially to be extended (even though it was done, one hack after the other), while the `Options` field can be extended with new fields at no cost. 

However, you think that the type of information stored in `SPRiNT`  has nothing to do with what is stored in `Options.FOOOF` and that it makes more sense to have it directly in the `timefreq` structure, then you can ignore this warning and keep it the way you did it. The design of this timefreq data structure is overall pretty dirty and I don't have anything cleaner to propose at the moment, so dirtier one way or another doesn't matter much :-)

2022-01-22 08:58 UTC, ftadel commented on toolbox/core/bst_memory.m
> +        GlobalData.DataSet(iDS).Timefreq(iTimefreq).SPRiNT = TimefreqMat.SPRiNT;
The field sprint should be added to `db_template.m`, in the `case 'loadedtimefreq'`.
Then its copy to GlobalData should be done above, with no extra tests, just like `sPAC`.

2022-01-22 08:58 UTC, ftadel commented on toolbox/gui/figure_timefreq.m
> +        elseif isSPRiNT
This block looks almost like the one above. 
You could probably factorize a few lines here.

2022-01-22 08:58 UTC, ftadel commented on toolbox/gui/panel_display.m
> +        if isfield(GlobalData.DataSet(iDS).Timefreq(iTimefreq), 'SPRiNT') && ~isempty(GlobalData.DataSet(iDS).Timefreq(iTimefreq).SPRiNT)
If you use directly the Timefreq structure: no need to test whether the field exists or not.
If you move it to `Options`, then leave it.

2022-01-22 08:58 UTC, ftadel commented on toolbox/gui/panel_display.m
> +            elseif isfield(GlobalData.DataSet(iDS).Timefreq(iTimefreq), 'SPRiNT') && ~isempty(GlobalData.DataSet(iDS).Timefreq(iTimefreq).SPRiNT)
Same comment.

2022-01-22 08:58 UTC, ftadel commented on toolbox/process/functions/process_sprint.m
> +    sProcess.Index       = 504;
This index conflicts with the others already in the Frequency menu.

To keep FOOOF/SPRiNT after FFT and PSD and before Hilbert (which makes sense):
you could edit the Index of `process_fft` and `process_psd` (start at 480).

2022-01-22 08:58 UTC, ftadel commented on toolbox/process/functions/process_sprint.m
> +    sProcess.options.spacer.Comment    = '';
You could add a new line at the beginning of the next label, to avoid this extract option entry.
E.g. `sProcess.options.fooof.Comment    = '<BR><BR>specparam options:';`

2022-01-22 08:58 UTC, ftadel commented on toolbox/process/functions/process_sprint.m
> +    % Spacer between option sets
Same comment.

2022-01-22 08:58 UTC, ftadel commented on toolbox/process/functions/process_timefreq.m
> +        case 'process_sprint',        strProcess = 'SPRiNT';
There was some sort of loose convention to use only lower case here.
Maybe you could keep it lower case too.

2022-01-22 08:58 UTC, ftadel commented on toolbox/process/functions/process_timefreq.m
> +            case 'SPRiNT',    tfOPTIONS.Comment = 'SPRiNT';
tfOPTIONS.Method: lower case
tfOPTIONS.Comment: anything

2022-01-22 08:58 UTC, ftadel commented on toolbox/timefreq/bst_sprint.m
> +function [TF, Messages, OPTIONS] = bst_sprint(F, sfreq, RowNames, OPTIONS)
I did not review this function.

2022-01-22 08:58 UTC, ftadel commented on toolbox/timefreq/bst_timefreq.m
> +        if strcmp(OPTIONS.Method,'SPRiNT')
Lower case?

2022-01-22 08:58 UTC, ftadel commented on toolbox/timefreq/bst_timefreq.m
> +        case 'SPRiNT'
Lower case?

2022-01-22 08:58 UTC, ftadel commented on toolbox/core/bst_memory.m
> +        if strcmp(TimefreqMat.Method, 'SPRiNT')
Lower case? (see comments in process_timefreq)

2022-01-22 08:58 UTC, ftadel commented on toolbox/gui/figure_timefreq.m
> +        isSPRiNT = isfield(GlobalData.DataSet(iDS).Timefreq(iTimefreq), 'SPRiNT') && ~isempty(GlobalData.DataSet(iDS).Timefreq(iTimefreq).SPRiNT);
If you use directly the Timefreq structure: no need to test whether the field exists or not.
If you move it to Options, then leave it.

2022-01-22 17:00 UTC, lucwilson commented on toolbox/core/bst_memory.m
> +        isSPRiNT = isfield(GlobalData.DataSet(iDS).Timefreq(iTimefreq), 'SPRiNT') && ~isempty(GlobalData.DataSet(iDS).Timefreq(iTimefreq).SPRiNT);
> If you decided on this solution to correct a previous choice that you regret
You've caught me in the act! I'm not a big fan of the current layout for FOOOF structures (being nested within the options) but after reading your explanation I understand its merits. I think dirtying up the Options structure is probably the best way forward, and will be rearranging the code to align with this decision. It seems to be the path of least resistance based on your other comments, anyway ;)

2022-01-22 17:14 UTC, lucwilson commented on toolbox/process/functions/process_sprint.m
> +    sProcess.Index       = 504;
I've adjusted indices such that `process_fft` = 480, `process_psd` = 481, `process_fooof` = 501, and 'process_sprint' = 502. There are no longer any conflicts.
Though it wasn't my original intention, this has led to FOOOF being grouped with fft and psd, while SPRiNT is grouped with other the time-frequency analysis methods, which I think is fitting.

2022-01-22 17:27 UTC, lucwilson commented
Updates finished, see de9e5ee for summary (esp. changes to FOOOF references, gotta get with the times)!

Thank you for reviewing @ftadel! If there are any further changes or improvements to be made, just let me know :)

2022-01-24 08:39 UTC, ftadel commented
It looks great, thanks!

> Though it wasn't my original intention, this has led to FOOOF being grouped with fft and psd, while SPRiNT is grouped with other the time-frequency analysis methods, which I think is fitting.

I moved SPRiNT next to FOOOF (moving the separator).
If you prefer having it in the time-frequency block, please move it after the last process in this block (instantaneous frequency).

> I'm not a big fan of the current layout for FOOOF structures (being nested within the options)

If you ever want to change this, it is possible to change the implementation in the code, and then modify the function `in_bst_timefreq.m` to add a block that converts the old FOOOF/SPRiNT structures into the update ones.

> A tutorial has already been developed using the tutorial dataset and can be found at https://neuroimage.usc.edu/brainstorm/Tutorials/SPRiNT.

I added the link to the Tutorials page.

2022-01-24 08:44 UTC, merged

2022-01-24 09:04 UTC, ftadel commented
> I moved SPRiNT next to FOOOF (moving the separator).
If you prefer having it in the time-frequency block, please move it after the last process in this block (instantaneous frequency).

After merging this, I wonder if it would not be more intelligible for the users to separate a bit better the computation part (FFT, PSD, wavelets...) and the modelling (specparam and SPRiNT).
Maybe moving them both between "Instantaneous frequency" and "Group in time or frequency bands"?

> A tutorial has already been developed using the tutorial dataset and can be found at https://neuroimage.usc.edu/brainstorm/Tutorials/SPRiNT.

Could you please add also something to the News page?
In a new section "January 2022", a couple of lines (a teaser, not an abstract) with a representative screen capture (not too large) to introduce the method and the tutorial, similarly to what was done for FOOOF:
https://neuroimage.usc.edu/brainstorm/News#Spectrum_analysis
Thanks!