Update coherence 2021 scripts
brainstorm-tools/brainstorm3 pull request #488
Opened 2022-01-25 15:59 UTC by rcassani

2022-01-25 16:04 UTC, rcassani commented
@ftadel, what do you think of hiding the grayed option **Imaginary Coherence (before 2019)** from the GUI in the coherence 2021 processes?

2022-01-28 18:36 UTC, ftadel requested changes

2022-01-28 18:36 UTC, ftadel commented on toolbox/connectivity/bst_connectivity.m
> +            if ~isempty(OPTIONS.MaxFreq) && (OPTIONS.MaxFreq ~= 0) && ~isempty(OPTIONS.MaxFreqRes)
I don't understand this part.
The option MaxFreq exists in the new coherence processes too, and need to be handled here.

2022-01-28 18:41 UTC, ftadel commented
> @ftadel, what do you think of hiding the grayed option Imaginary Coherence (before 2019) from the GUI in the coherence 2021 processes?

I think it's better to keep it for now.
Users who started a study with the old measure (which is not that old, considering how long a study can last...) may need to be able to reproduce results that they've obtained before, or when including new participants in an existing study they would need to compute the same measure as before.

It's clearly visible that we don't recommend using it, therefore I don't think it adds confusion or a major readability issue to the processs options.

2022-01-28 19:04 UTC, rcassani commented on toolbox/connectivity/bst_connectivity.m
> +            if ~isempty(OPTIONS.MaxFreq) && (OPTIONS.MaxFreq ~= 0) && ~isempty(OPTIONS.MaxFreqRes)
For the new coherence, the MaxFreq is handle inside bst_cohn_2021.m 020d57d74c2d142247ac9803e0c258758ee9ef2e
The this part may be needed only for the deprecated coherence.

2022-01-28 19:17 UTC, ftadel commented on toolbox/connectivity/bst_connectivity.m
> +            if ~isempty(OPTIONS.MaxFreq) && (OPTIONS.MaxFreq ~= 0) && ~isempty(OPTIONS.MaxFreqRes)
Ok, sorry for missing that.

2022-01-28 19:18 UTC, merged