Global PCA for scouts and/or unconstrained sources
brainstorm-tools/brainstorm3 pull request #559
Opened 2022-07-12 20:20 UTC by Moo-Marc

**Description**

This PR implements computing PCA across all files/epochs at once ("global pca") instead of separately for each file ("per-trial PCA").  It applies to extracting scout time-series, either through process_extract_scout or indirectly (e.g. for connectivity on scouts), and to "flattening" unconstrained source orientations to one source per vertex.

**Justification**

Following tests of various PCA procedures on the introductory tutorial data, it seems the feature of  has the following advantages:

1. It avoids sign flipping issues between trials.  In particular, currently, PCA for unconstrained sources fails because of this, and the [solution](https://github.com/brainstorm-tools/brainstorm3/pull/534) proposed by @rcassani for scouts does not work for unconstrained source flattening.
2. It seems on par with per-trial PCA for extracting source activity across different conditions (e.g. many "standard" vs few "deviant" trials in the introduction tutorial), and should be more robust with very few or very short trials (though tests show per-trial is pretty robust too).  
3. It may simplify interpretation of comparisons when the same component is applied across conditions.
4. It allows visualising the scout component maps.
5. It can be used to do both scout and flattening in a single step, which is slightly better than doing flattening separately first, and noticeably better than doing scout extraction on x,y,z separately first.  Here "better" means it keeps more source power, which is what PCA maximises.  It achieves this by taking into account the full scout source covariance matrix, whereas doing it in 2 steps ignores some of the source pairs (e.g. location 1 x vs location 2 y).

Among these points, only 1 is pretty serious, but I think it all adds up to a good case for including this feature, and even using it as the default instead of per-trial PCA.  A warning about the sign issue should also be added to per-trial PCA for flattening.

**Implementation**

This initial PR is a rough draft, how I implemented it for testing only.  In particular, it has a bunch of extra options that would be removed (pcagt, pcag3, pcagx).

Currently, the functions that do PCA for scouts or flattening often see only one file at a time.  Therefore, I implemented this using the data covariance matrix.  The user would first compute the data covariance on all trials, and that would be used to compute the global PCA and applied to each file or to file averages, depending on the use case.  Unfortunately, this means the same PCA decomposition is computed repeatedly each time it is applied to a file, but this was the simplest way to do it without creating new files (e.g. PCA kernels), or new fields (e.g. in the channel file, or inverse kernel file).  And it is reasonably fast enough, equivalent to the current per-trial PCA.

I'm open to suggestions on how else we could implement this.

**Documentation**

Do we want to save somewhere a summary of the tests and results that show how the various PCA procedures perform?  I have a couple slides now, but I could for example save it as a forum post which we could link to in the tutorials?

2022-07-24 18:05 UTC, ftadel commented
> Even though it's been like this for some time, I think the broken flattening PCA should be fixed asap.

The PCA option is not used in any of our recommended pipelines, so it is not an emergency to do anything with it.
All the things that are in the standard pipelines is much more urgent to fix (like the statistics for instance: https://github.com/brainstorm-tools/brainstorm3/issues/141, https://github.com/brainstorm-tools/brainstorm3/issues/225...)

> Given this, I propose that I simplify this PR to only keep the global PCA option for flattening as a first step. Once reviewed and merged, I can introduce the rest of the changes for later review. Once the code is cleaned, I think it shouldn't be too long to review. 

Sounds good.

2022-07-29 21:25 UTC, Moo-Marc commented
Really trimmed down the changes to only unconstrained source flattening as a first step, for easier review.
Only process_source_flat has access to the PCA function for orientations at the moment.

2022-09-10 17:33 UTC, ftadel requested changes

2022-09-10 17:33 UTC, ftadel commented on toolbox/inverse/bst_source_orient.m
> +%    - SourceCov    : [Nvertices x Nvertices] Covariance matrix between rows of SourceValues. Used with Function='pcag' only.
From what I understood, you aimed to pass a [Nsources x Nsources] matrix here.
This doesn't work: it's going to be way too big. Most users don't have 64Gb of RAM.
You need to optimize this input. Maybe passing the data covariance + the kernel, and optimize the computation so that it never computes the full source covariance

2022-09-10 17:33 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +            Fs = permute(Fs, [3,2,1]);
Is what you removed and what you added really equivalent here?

2022-09-10 17:33 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +    U = U(:,1);
You're actually modifying the function, making the software not backward compatible, and older results not reproducible.

In our preliminary discussion, one request I had was to add new options and keep the old ones working with no modification.
Please reorganize your developments so that a previous execution of `process_source_flat` keeps on producing the exact same results as before even with the new version of the software, and that newly created scripts have an additional option to compute your new PCAg function.

2022-09-10 17:33 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +            end
This logic doesn't work.
1) This is a very bad practice to have a return in a middle of a loop.
2) If the user passes multiple files that do not relate to the same ImagingKernel, you need to group them by inverse solution file, loop on each group, and produce one file in output per group.
Please reorganize the code of this function in a cleaner way.

2022-09-10 17:33 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +                                       '<B>PCA</B>: First mode of svd(x,y,z)<BR>(requires pre-computed data covariance across epochs)'; ...
Use has to be warned that this is PCAg.
Also, Sylvain requested to have access to both PCA (trial-wise) and PCAg.

2022-09-14 17:55 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +    U = U(:,1);
The option I add of not removing the baseline here is off by default.  Everything is still compatible and reproducible.

2022-09-14 18:01 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +                                       '<B>PCA</B>: First mode of svd(x,y,z)<BR>(requires pre-computed data covariance across epochs)'; ...
This first PR was only to fix the problematic sign-flipping issues.  We don't want to keep previous bugged code just for reproducibility, right?  I will add all the options we discussed in the next PR.

2022-09-14 18:25 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +    U = U(:,1);
Anyway, it wasn't used yet in this PR so I guess it can be added back later.  But this option will be important: when users compute their data covariance matrix, they chose a baseline to remove the offset.  It's not a good idea to again remove the offset later on the whole trials without the user knowing about it.

2022-09-14 18:36 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +        case 'pcag',      Method = 'pcag'; fileTag = 'pcag';
I don't like pcag as a file tag.  "global PCA" is vague (it was originally about doing flattening and scout together, which didn't have an obvious name).  We should simply call this option PCA across trials (PCA-a?) vs PCA per trial (PCA-t?).

2022-09-14 18:51 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +function [Fs, PcaOrient] = bst_scout_value(F, ScoutFunction, Orient, nComponents, XyzFunction, isSignFlip, scoutName, Cov)
It doesn't matter much, but this name won't make as much sense once I add back PCA across trials for scouts.  It also outputs a PCA component, but it's no longer an orientation.

2022-09-14 20:02 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            Fs = permute(Fs, [3,2,1]);
Yes.  Here there's a single source (scout function was applied), so it's size 1,nTime,nComp.  Examples: 
```
>> a = 1:5; a(:,:,2)=6:10;
>> a = permute(a,[3 2 1])
a =
     1     2     3     4     5
     6     7     8     9    10
>> a = 1:5; a(:,:,2)=6:10; a(:,:,3)=11:15;
>> a = permute(a,[3 2 1])
a =
     1     2     3     4     5
     6     7     8     9    10
    11    12    13    14    15
```

2022-09-15 14:35 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +function [Fs, PcaOrient] = bst_scout_value(F, ScoutFunction, Orient, nComponents, XyzFunction, isSignFlip, scoutName, Cov)
Please feel free to change it to something else that makes more sense.
I just felt that `Comp` was not clear enough, I tried to make it more readable.

2022-09-15 14:36 UTC, ftadel commented on toolbox/inverse/bst_source_orient.m
> +%    - SourceCov    : [Nvertices x Nvertices] Covariance matrix between rows of SourceValues. Used with Function='pcag' only.
I'm not sure I understand why you marked this as resolved.
Can you please explain? 
Thanks

2022-09-15 14:55 UTC, ftadel requested changes

2022-09-15 14:55 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +    U = U(:,1);
I'm sorry, I don't understand your reply.

I was pointing at the fact that you replaced:
```
    S = diag(S);
    explained = S(1).^2 / sum(S.^2);
    % Find where the first component projects the most over original dimensions
    [tmp__, nmax] = max(abs(U(:,1))); 
    % What's the sign of absolute max amplitude along this dimension?
    [tmp__, i_omaxx] = max(abs(F(nmax,:)));
    sign_omaxx = sign(F(nmax,i_omaxx));
    % Sign of maximum in first component time series
    [Vmaxx, i_Vmaxx] = max(abs(V(:,1)));
    sign_Vmaxx = sign(V(i_Vmaxx,1));
    % Reconcile signs
    F = sign_Vmaxx * sign_omaxx * S(1) * V(:,1)';
    % Add the weighted average back to the signal
    % The mean is tderived from the original signal averages weighted by their respective contributions to the first singular vector
    F = F + sign_Vmaxx * sign_omaxx * U(:,1)' * Fmean;
```

with:
```
    % Signal decomposition / Remove average over time for each row
    [U, S] = svd(bst_bsxfun(@minus, F, mean(F,2)), 'econ');
    S = diag(S);
    explained = S(1).^2 / sum(S.^2);
    U = U(:,1);
```

I have a hard time believing that "Everything is still compatible and reproducible".
If it is not possible to produce previously obtained results with an unmodified script, it is not reproducible.

2022-09-15 14:55 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +                                       '<B>PCA</B>: First mode of svd(x,y,z)<BR>(requires pre-computed data covariance across epochs)'; ...
> We don't want to keep previous bugged code just for reproducibility, right?

Yes, I think we do, whenever we can.
In my understanding, this is what reproducibility means.
For the past 10 years, we continuously updated this code with newer version, that invariably was declared "bugged" a few months or years later. Whatever code you implement now will probably be declared "bugged" as well, at some point. It is important to keep track of what we do with unstable code like this, so that: 1) old scripts keep on producing the same results, and 2) a future student in 2030 will be able to re-run all the previous attempts and finally decide on what is the best solution that was proposed over the years.

But maybe I'm not aiming at the right targets.
Since at the moment we don't recommend using PCA, I'd be less worried to modify the existing methods. But still, that would break the notion of reproducibility.

@sbaillet @rcassani 
What is your opinion on this topic?

2022-09-15 14:55 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +        case 'pcag',      Method = 'pcag'; fileTag = 'pcag';
I have no opinion on the tag that is used.
Please decide on what you find is best, or ask @rcassani or @sbaillet for suggestion.

But if the old tag is "pca", then the new one should be something else to be able to differentiate the files in the database and the methods in the scripts.

2022-09-15 15:09 UTC, Moo-Marc commented on toolbox/inverse/bst_source_orient.m
> +%    - SourceCov    : [Nvertices x Nvertices] Covariance matrix between rows of SourceValues. Used with Function='pcag' only.
Oh, sorry, my comment didn't save.  I will change the comment.  It's actually 3x3xNvertices here.

2022-09-15 15:17 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +    U = U(:,1);
I see.  I thought it was about the non-baseline removal option which you removed here.

This change is the sign-flip fix from Raymundo.  I agree with keeping many things as (sometimes hidden) options, but not what is clearly broken.  For reproducibility, with version control, users can use any previous version.  Of course we don't currently have version numbers/tags, so it would be the responsibility of users to note the Brainstorm version they used.

2022-09-15 15:26 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +                                       '<B>PCA</B>: First mode of svd(x,y,z)<BR>(requires pre-computed data covariance across epochs)'; ...
> We don't want to keep previous bugged code just for reproducibility, right?

I meant that with the understanding that everything exists in the version control system, so reproducibility is always possible.  I would suggest only keeping "live", things that should still be used.  In a case such as this, it's not just a better implementation or newer method, it was not doing what users (and we) expected.  I call that a bug.  Even if a user has started doing PCA and wants to continue, we have a responsibility to let them know that the previous implementation was broken and shouldn't be used.

2022-09-15 17:17 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +    U = U(:,1);
As much as I can, for the standard recommended pipelines, I would like the same script to be able to run identically even with different versions of Brainstorm. Except indeed for obvious bugs. 
However, this PCA thing is not that clearly **a bug**, as it's been modified multiple times with the approval of all the team, and there is no clear ground truth to any dimension reduction technique.

I'm fine with considering this as a bug, and just replace the code as you suggested, but I'd like to get the explicit approval from the authors of this code (@sbaillet @dimitriospantazis @jcmosher @richardmleahy) that they all agree that what they wrote is _a bug_ and that your modified version is _not a bug_.

Unfortunately, I don't think this can be discussed over github, as they would not read through all this and dive in the code.
Could you please prepare a demo to illustrate your suggested code replacement, and present it at the meeting next Wednesday? (you could send an email to at least Sylvain and Richard to put it officially on the agenda).
Thanks

2022-09-15 19:07 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +    U = U(:,1);
Sure let's confirm in a meeting. But this was already presented in detail to the team by @rcassani a while ago, with https://github.com/brainstorm-tools/brainstorm3/pull/534. I don't think anybody remembered why it was done the way it was previously, but the goal was to get a consistent sign. Raymundo clearly showed the sign flips between epochs, leading to the bad results he first saw with PCA as scout function in connectivity. And he showed his solution works well on scouts.

> no clear ground truth to any dimension reduction technique

True, but that's not the issue here. PCA has a sign ambiguity, independently of what it is used for (here dimension reduction). If we apply it on each epoch separately, we have to be consistent in the choice of sign. Otherwise, any further computation that combines the epochs in any way (averaging, connectivity, etc.) will not give the expected result.

2022-09-15 19:12 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +                                       '<B>PCA</B>: First mode of svd(x,y,z)<BR>(requires pre-computed data covariance across epochs)'; ...
Agreed. I'll add the two options in this PR. I'm working on it. 
Recall that the per-trial option will still change since it also requires a sign flipping solution, different than the one for scout PCA.

2022-09-19 16:55 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +            end
Changed as requested.  
I wasn't sure if there was a better way to get the kernel file than extract it from the "link|kernel|data" composite FileName. Would be nice if it were saved as its own field.

2022-09-19 17:09 UTC, Moo-Marc commented
Requested changes were made, so ready for another review once the "bugness" question is decided. 
I added back flattening PCA per epochs, with sign correction based on PCA across epochs.
Some changes were made for efficiency, but it still takes quite a while to run flattening PCA per epochs: ~10 minutes for 192 epochs, vs seconds for across epochs which only runs once and saves a kernel for all files.
Tested, and confirmed similar results (left per epoch, right across epochs):
![Flattening_160ms_20220919](https://user-images.githubusercontent.com/31040756/191073631-600eaef0-bc6d-4a45-beea-eaf0cd402ab3.png)

2022-09-21 13:40 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +            end
Please use `file_resolve_link`, it returns the kernel file + the data file.

2022-09-21 15:55 UTC, ftadel submitted a review, later dismissed
Some more things to fix.

Another thing to think about:
Where would you see this documented in the tutorials?
(at the moment, it is not documented at all...)

2022-09-21 15:55 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +            ResultsMat.ImagingKernel = ResK.ImagingKernel;
In this case, you are loading twice the file, and adding and `ImagingKernel` field to a structure that already contains a `ImageGridAmp` field, making it an invalid data structure (it's one or the other).

In the cases you need the ImagingKernel, please load the file only once, with `ResultsMat = in_bst_results(sInputs(iInput).FileName, 1);`

2022-09-21 15:55 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +                OrientCov = squeeze( sum(bsxfun(@times, sum(bsxfun(@times, permute(Ker, [3,4,1,2]), DataCov.NoiseCov(ResultsMat.GoodChannel, ResultsMat.GoodChannel)), 1), ... % (1, nChan, nComp, nSou
On the tutorial dataset, this line generates the following error on my computer:
```
Error using bsxfun
Requested 274x274x3x15002 (25.2GB) array exceeds maximum array size preference (15.9GB). This might cause MATLAB to become unresponsive.
```

We can't assume that users have 25Gb of RAM available for this process.

2022-09-21 15:55 UTC, ftadel commented on toolbox/math/bst_scout_value.m
>  %     - XyzFunction    : String, function used to group the the 2 or 3 components per vertex: return only one value per vertex {'norm', 'pca', 'none'}
Add pcaa in the list.
And maybe some description explaining what is happening with the interaction of the two options ScoutFunction/XyzFunction, at the end of the header?

2022-09-21 15:55 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +                SharedFile = bst_process('GetNewFilename', bst_fileparts(sStudy.FileName), [FileType '_KERNEL_' fileTag]);
Input kernel file: `results_dSPM-unscaled_MEG_KERNEL_220921_1723.mat`
Output kernel file: `results_KERNEL_pcaa_220921_1727.mat`

It would be better if the output filename could keep the tags from the input file, it would help tracking where is the flattened file came from.
Maybe just append "pcaa" at the end of the existing kernel filename?

2022-09-21 15:55 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +            %warning('This older PCA implementation suffers from sign flipping between epochs.');
If this is not the old implementation: remove the comment

2022-09-21 15:55 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
Is the goal of this only to be reproducible between two identical calls of the same process on the same files?
Otherwise, for what reason would we enforce two epochs to have their PCA oriented along a similar direction?

It prevents from calling the PCA flattening on a single file, e.g. a subject-level average, resulting of the averaging of multiple files. It is OK, but since this is a one of the recommended workflows (https://neuroimage.usc.edu/brainstorm/Tutorials/Workflows#Unconstrained_cortical_sources), it requires some adjustments in the procedures if you want to make this modified process compatible with them.

2022-09-21 17:14 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +        case 'pcaa',  fileTag = 'pcaa';
**A**cross epochs

2022-09-21 17:16 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> -if (nargin < 7) || isempty(scoutName)
Right, noted.

2022-09-21 17:17 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            %warning('This older PCA implementation suffers from sign flipping between epochs.');
Kept it commented for now if we need to keep the old implementation, since it's not decided yet.

2022-09-21 17:30 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
This is the PCA sign ambiguity question, which we need to make consistent both between calls and importantly between epochs so that averaging, connectivity, etc. doesn't cancel out when combining epochs.

> It prevents from calling the PCA flattening on a single file

Not really. Recall that it uses the data covariance to compute the pcaa. The call just needs to provide it, which process_source_flat now does. I'll search if there are other ways this gets called for flattening.  Maybe we'll have to remove "shortcuts" where it's incorporated into other processes and require it being done separately.

2022-09-21 17:35 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +    %sign_meancorr = sign(sum(U(:,1)));
I'll try.  But it's all an explanation of the sign correction in the following line. Since the math simplifies a lot, it's not clear why sign(sum(U)) makes sense, so it's important to keep this.

2022-09-21 17:39 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +    sProcess.options.pcamode.Comment = {'once across epochs', 'separately for each epoch', 'PCA computation:'; ...
> 1. and you should therefore make it conditional to the selection of "pca" in the first option

I wanted to, but I think the conditional stuff Martin added only works with checkboxes as a controller, right?

2022-09-21 18:24 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +    OutputFiles = cell(1, numel(sInputs));
{} Even if it ran successfully for some of the files before the error?  Or you meant it shouldn't contain empty cells, i.e. grow as we loop?

2022-09-21 18:51 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
>  %     - XyzFunction    : String, function used to group the the 2 or 3 components per vertex: return only one value per vertex {'norm', 'pca', 'none'}
> what is happening with the interaction of the two options ScoutFunction/XyzFunction

Yes that will be important, but let's wait until the next PR that will add changes to the scout function PCA.  For both PCAs, flattening should be done first, which is the opposite of what this function currently does.  So there's more to think about.

2022-09-21 19:23 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
I verified that no other function can currently call this with XyzFunction 'pca'.  I'm making a note that we should eventually review each of these to see what options we want, once PCA is settled.

- view_scouts, process_extract_scout, process_source_atlas: norm or none
- bst_timefreq: sum (but TODO for complex values)
- process_canoltymap: sum for TF, mean for ERP
- process_pac, process_pac_dynamic: mean
- bst_connectivity: max
- bst_memory: min for p-values, absmax for t-values, max for stat, rms for results

2022-09-21 20:42 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +            ResultsMat.ImagingKernel = ResK.ImagingKernel;
Right, I can use kernel only for pcaa now that I only save a kernel. And for pca I can load the full data and discard the kernel after I have PcaAcross.

2022-09-21 21:20 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +function [ResultsMat, PcaOrient] = Compute(ResultsMat, Method, Field, sStudy, PcaOrient)
Will do.

2022-09-21 22:20 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +                SharedFile = bst_process('GetNewFilename', bst_fileparts(sStudy.FileName), [FileType '_KERNEL_' fileTag]);
Done (in next commit)

2022-09-21 22:24 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +                if numel(sStudy.NoiseCov) < 2
That was in case it were called from elsewhere.  Removed in next commit.

2022-09-21 22:24 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +                    error('PCA flattening only available for imaging kernel files.');
Also tested in the calling function.  Removed in next commit.

2022-09-21 23:53 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +                OrientCov = squeeze( sum(bsxfun(@times, sum(bsxfun(@times, permute(Ker, [3,4,1,2]), DataCov.NoiseCov(ResultsMat.GoodChannel, ResultsMat.GoodChannel)), 1), ... % (1, nChan, nComp, nSou
Indeed.  We'd need pagemtimes here.  I found a way to loop once on components instead. It should stay under 100MB.

2022-09-22 08:08 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
> > It prevents from calling the PCA flattening on a single file
> Not really. Recall that it uses the data covariance to compute the pcaa. The call just needs to provide it, which process_source_flat now does. 

The two problems I see with the current process:
- It requires a kernel, and is therefore not applicable to any source file that was post-process, or averaged across runs (which only have ImageGridAmp and no ImagingKernel, e.g. Z-scored maps)
- In the case of averages between multiple runs, there is no data covariance available in the folder, the process crashes, while in principle, the method you propose should be applicable to single files, with no data covariance and no imaging kernel.

I'm sure this limitation would cause problems in some pipelines, and would cause misunderstanding and productivity  because this limitation cannot be anticipated.
I think that for the versatility of the process, the processing stream should be refined, for example:
- If there is no ImagingKernel: use the ImageGridAmp, ignores the data covariance, and saves only one single flattened file
- If there is only one file in input (or two? or less than half of the trials of the folder? or any other heuristic?): save independent files instead of kernel files that create again tons of links. 

Use case: for connectivity, you typically want to flatten individually all the trials. But for group-level statistics, you need to flatten only the averages. It would get very quickly annoying if when processing only the average, either it crashes (because there is no Kernel) or it recreates hundreds of new unwanted links for all the trials, making the source files more difficult to select programmatically.

2022-09-22 08:11 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +    sProcess.options.pcamode.Comment = {'once across epochs', 'separately for each epoch', 'PCA computation:'; ...
No, it works with radio buttons as well (at least since I fixed it).

But I recommend you don't lose time in doing this. The usability would be definitely improved with only ONE flat list of THREE radio buttons, instead of 2+2 radio buttons with conditional behaviors.

2022-09-22 08:25 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +    OutputFiles = cell(1, numel(sInputs));
If there is one input file that can't be processed, you can decide on one of the two behaviors below:
1) It triggers an error: the process stops immediately calls `return`, no files are returned so that the calling script is informed that a blocking error occurred. OutputFiles must be set to {} before the function returns.
2) It triggers a warning: the process doesn't stop, it moves to the next iteration of the `for` loop with `continue` instead of `return`, reports a `Warning` instead of an `Error`. The corresponding item in the OutputFiles cell-array must be set to the original file (no empty cell allowed in the returned cell-array). 

The second option is less restrictive, but might not correspond to what we need here. In a full processing script, if the file can't be processed and is still with 3 components, you just can't move on as if nothing happened because the next process might crash in an ugly way or produce weird/unwanted results, causing a bug that might be difficult to detect. It's usually safer to generate clear errors, forcing the user to fix the issues, instead of allowing uncontrolled behaviors.

The only case where you can trigger a warning instead of an error is if the file is already flat (nComponents=1).

2022-09-22 08:27 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +            ResultsMat.ImagingKernel = ResK.ImagingKernel;
I think you should implement the two streams in parallel: 
- reading a kernel => saving a kernel
- reading a single file => saving a single file (no use of ImagingKernel)

2022-09-22 16:07 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +    OutputFiles = cell(1, numel(sInputs));
Ok I'll reset it before error returns.  
Note that yesterday I randomly looked at process_timefreq and bst_timefreq (I had them open) and it looked to me that it was returning a partially filled OutputFiles on an error.

2022-09-22 16:12 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +            ResultsMat.ImagingKernel = ResK.ImagingKernel;
It's not that simple.  We now always need the kernel to apply to the covariance matrix, even with pca where we use pcaa to fix the sign.  So both pca/a will no longer be possible on non-kernel files.  pcaa saves a shared kernel, pca saves a single-file kernel.  Next commit coming today.

2022-09-22 16:33 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
> But for group-level statistics, you need to flatten only the averages.

It's true that would be ok to do.  But if we allow running on single trials, it becomes very difficult to properly warn the user to never do it if there's subsequent steps that depend on the individual trial sign consistency.  (Actually, if doing group averaging, there's a question of between-subject sign consistency as well.  This requires further thought.)  Instead of allowing single trials because it's valid in some cases, I'd suggest not allowing and instead the flattening would have to be performed earlier in the pipeline, with a kernel, if users want to use PCA.

2022-09-22 16:49 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
> save independent files instead of kernel files

We only save a **shared** kernel when doing pcaa, which implies it's valid on all the data from the data covariance matrix.  Yes users can run it on a single file (actually makes sense since it only needs to run once) and it creates all the links.  For selecting the sources, there's now the added 'pcaa' part in the files.  I see these as minor inconveniences.  I believe this fits the philosophy of Brainstorm to not aim to maximize versatility, but ensure proper use of few valid options, right?

In terms of user friendliness and having fewer steps and links etc, I still think the best approach down the road is to have this PCA flattening as an option in the inverse process source model.  For now, I'd stick to have it as is (kernel only).

2022-09-22 18:11 UTC, Moo-Marc commented on toolbox/process/functions/process_source_flat.m
> +    sProcess.options.pcamode.Comment = {'once across epochs', 'separately for each epoch', 'PCA computation:'; ...
ok for flat. I can show it in our next Monday meeting and get feedback.

2022-09-22 20:44 UTC, Moo-Marc commented
Thanks Francois for all the useful comments. 

Regarding tutorials, how about a section for flattening right after the [Unconstrained orientations](https://neuroimage.usc.edu/brainstorm/Tutorials/SourceEstimation?highlight=%28unconstrained%29#Unconstrained_orientations) section in the source estimation tutorial, or in the advanced section?

2022-09-24 10:39 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +    OutputFiles = cell(1, numel(sInputs));
process_timefreq/bst_timefreq is indeed very messy in terms of error handling.
But it never returns empty cells in OutputFiles.

If you prefer returning partially filled OutputFiles (until it crashes), it would not change anything.
But please avoid risking having only warnings and empty cells: this would cause problems in bst_process.

2022-09-24 10:42 UTC, ftadel commented on toolbox/process/functions/process_source_flat.m
> +            ResultsMat.ImagingKernel = ResK.ImagingKernel;
We should be able to compute the pca without any data covariance.
The data covariance/kernel should be only an optimization of the computation/storage, not a requirement.

2022-09-24 10:54 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
So we wouldn't be able to flatten a single non-kernel file (a Z-scored average, possibly imported directly from another program) with PCA? The current version of the PCA "works well" in this case. Are you suggesting to remove this option from the possible pipelines?

It looks like there is some more work to be done to explain how this PCA fits in all the possible workflows involving unconstrained sources.

2022-09-24 11:00 UTC, ftadel commented
> Regarding tutorials, how about a section for flattening right after the [Unconstrained orientations](https://neuroimage.usc.edu/brainstorm/Tutorials/SourceEstimation?highlight=%28unconstrained%29#Unconstrained_orientations) section in the source estimation tutorial, or in the advanced section?

Maybe an advanced section just after: https://neuroimage.usc.edu/brainstorm/Tutorials/SourceEstimation#Averaging_normalized_values

2022-09-29 20:31 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
Ok, I thought a bit more about it and we can add non-kernel files.  

There will be more options.  I think it deserves a separate "PCA options" panel, as it will apply to scout PCA too:

- PCA "type": across epochs, per epoch with sign consistency, (per epoch with arbitrary sign - if we want to keep it)
- Use pre-computed data covariance (much faster, but requires kernel files only)
- For covariance: baseline and active time windows, DC offset.
  Possibly some options like the averaging process, deciding how to group:
- Eventually, for multiple subjects: "group PCA" (like group ICA)? or separately per subject
- For multiple studies: weighted or equal averaging

Is there a recommended way to sort inputs so they are ordered by subject, study, and condition?  I was thinking text sorting by FileName. 

For single non-kernel files though, we'd have to give a strong warning.  If the user wants to contrast two averaged conditions for example, they should not run them separately or the sign might not match. 

For group averaging, it's another level of difficulty for matching signs.  Something to be investigated further.  Probably we want to warn about this for now, at least in the tutorials.

2022-09-30 09:09 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
> PCA "type": across epochs, per epoch with sign consistency, (per epoch with arbitrary sign - if we want to keep it)

This can added as 2 (or 3) options for flattening or for scout function, no need to add any extra panel.

> Use pre-computed data covariance (much faster, but requires kernel files only)
> For covariance: baseline and active time windows, DC offset.
> Possibly some options like the averaging process, deciding how to group:
> For multiple studies: weighted or equal averaging
> 
> For single non-kernel files though, we'd have to give a strong warning. If the user wants to contrast two averaged conditions for example, they should not run them separately or the sign might not match.

This sounds too complicated. We can't ask the users to fill in a full window of options in order to get their scouts time series. What we propose must remain accessible to the average user, unless you want to make this an advanced option only accessible to experts and not recommended anywhere.
Can't you simply re-use the data covariance available in the database for this file, instead of asking all the input parameters to compute it again? And does it make sense to compute a data covariance from an average anyway?

If you can't make it easily accessible without a full panel of options, just drop this option of making it accessible to non-kernel files.

> Eventually, for multiple subjects: "group PCA" (like group ICA)? or separately per subject
> For group averaging, it's another level of difficulty for matching signs. Something to be investigated further. Probably we want to warn about this for now, at least in the tutorials.

For group analysis, the source signals are always flattened and **rectified** - no sign problem anymore. Please try to limit the scope of the solutions you're exploring to what we actually need, which is documented in the Workflows page:
https://neuroimage.usc.edu/brainstorm/Tutorials/Workflows#Unconstrained_cortical_sources

> Is there a recommended way to sort inputs so they are ordered by subject, study, and condition? I was thinking text sorting by FileName.

You can group the files using the field SubjectFile or ChannelFile of the input structures. All the possible grouping solutions are coded in `process_average.m`.
Simple examples grouping by channel file (which is maybe the only thing you need) are available in various processes, like `process_headpoints_add` or `process_montage_apply`. Search for `{sInputs.ChannelFile}`.

2022-09-30 20:04 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
> Can't you simply re-use the data covariance available in the database for this file

No, not without a kernel.  That's why I had it this way to start.

> This sounds too complicated.

It's not that bad, but we could hide the last two things for now, so just have the covariance options.  I wanted to add the baseline/active window anyway to replace the automatic DC offset removal that used to be done for PCA.

> compute a data covariance from an average

No, I average the covariances. 

> For group analysis, the source signals are always flattened and **rectified**

That's one solution, and the one I'd prefer in many cases.  But is that just the recommended workflow or is it enforced in group averaging?  Would it for example prevent averaging of signed connectivity results without applying abs?


I'm almost done with this change.  It wasn't small, but it will now properly deal with files from multiple subjects (treat them separately for now), and multiple conditions, which I hadn't considered yet but it's good to combine them.  It will save a shared kernel for conditions where all files are links, or single-file kernels or full results for other files.  It's longer if there are non-links because we have to loop over those files twice.

2022-10-03 12:21 UTC, ftadel commented on toolbox/math/bst_scout_value.m
> +            Fs = sum(bsxfun(@times, permute(PcaFirstComp, [2,3,1]), F), 3); % dot product of Comp with F on 3rd dim, gives size (nRow, nTime)
> But is that just the recommended workflow or is it enforced in group averaging?

Heavily recommended, only solution documented, but not enforced.

>  Would it for example prevent averaging of signed connectivity results without applying abs?

It would not prevent any averaging or statistical tests on signed data, not even generate a warning.
It is only for source-level data that this is recommended.
For the moment, there is no clear workflow documented for group-level statistics on connectivity measures.

2022-10-21 20:57 UTC, Moo-Marc commented
Hi @ftadel,
The code for PCA flattening is ready for review.  It now works for non-kernel files, and across conditions/studies. (recall I kept non-kernel files for now since they'll be needed for scouts).  If you can have a look to see how the flattening process is now organized and think a bit about scouts, I'd appreciate your input.  I'm not sure yet what's the best approach since there are 2 extra levels of looping in process_extract_scout (scouts and frequencies).

There's now a new PCA options panel:
![PcaFlatProcess](https://user-images.githubusercontent.com/31040756/197287197-8639336a-75bf-4920-8c4f-05cb8424d8c2.png)
![PcaOptions](https://user-images.githubusercontent.com/31040756/197286351-29f979ec-a49e-4e0b-9f35-b663c02628fc.png)

There's one useability bug I haven't yet figured out: when modifying options in the panel and clicking ok, it goes back to the process window. If we click the Edit button again, the panel options are reset, it doesn't keep the previous settings.

2022-10-21 21:00 UTC, Moo-Marc commented
Note that I did pretty thorough tests of various inputs and settings.  In particular, I confirmed the results are identical when using pre-computed data covariance or not, with the same settings.

2023-03-20 18:12 UTC, Moo-Marc commented
Finally the PR is ready for review again.

Scout and flattening PCA are implemented and all connectivity processes updated.  Most of the file manipulation for PCA across files is now done in a new bst_pca function.

Still to do: 

- Documentation.
- Possibly: change bst_process to do the temporary scout extraction instead of each process.
- Time-frequency processes that use scouts.

2023-03-28 19:20 UTC, rcassani commented on toolbox/math/bst_scout_value.m
> +%       to match the scaling of 'mean', and to be more easily comparable between scouts.
It seems such scaling is not applied for `PCA` nor for `FastPCA` ScoutFunctions

2023-03-28 20:09 UTC, Moo-Marc commented on toolbox/math/bst_noisecov.m
> +isProgress = length(DataFiles) > 1;
The progress increments as it loops through the input files. For one file it just appears and disappears (rather quickly), which is just not useful. Plus it may interfere with any other progress bar that was ongoing: this was the case when I was using it for pca, but no longer.

2023-03-28 20:12 UTC, Moo-Marc commented on toolbox/process/functions/process_extract_scout.m
> +    sProcess.options.concatenate.Class   = 'notpca';
I actually don't know when it's ever useful, why it was added.  It could eventually be added back, but it complicates the already many possibilities of output files with PCA...  So I thought we should discuss if it would actually be useful before doing it.

2023-03-28 20:43 UTC, Moo-Marc commented on toolbox/math/bst_pca.m
> +% components, and for pca and pcai we compute individual file PCA components. This however means
You mean in the history?  I guess we could, like it's done for concatenated output in extract_scout.  Yet this is not done for other processes, like covariance or inverse models, right?

2023-03-28 21:35 UTC, Moo-Marc commented on toolbox/math/bst_scout_value.m
> +%       to match the scaling of 'mean', and to be more easily comparable between scouts.
Not for FastPCA on purpose: I think we'll get rid of it (from the interface).  
For the old PCA, it should be applied.  It's my mistake: I had to temporarily disable it to confirm it was otherwise the exact same result as the old code.  Turned back on in a new commit.

2023-03-28 22:59 UTC, rcassani commented on toolbox/math/bst_pca.m
> +% components, and for pca and pcai we compute individual file PCA components. This however means
Yes, something like in History, or in the Options.
Other kernels save information of the noise and data covariance matrices in Options.NoiseCovMat.History and Options.DataCovMat.History respectively

2023-03-29 14:58 UTC, Moo-Marc commented on toolbox/math/bst_pca.m
> +% components, and for pca and pcai we compute individual file PCA components. This however means
Ok, I didn't know it was in the covariance files.  Lets do it the same way then, directly in History, to save the list of input files.

2023-03-30 16:07 UTC, Moo-Marc commented on toolbox/connectivity/bst_connectivity.m
> It would be necessary to keep the original `sInputB` to properly set the parent file.

Or we don't delete the result files in that case?  But if we're really not allowed to have those types of result files, I guess we need to.  But bst_connectivity didn't have sInputs until now, only the file names; and we still have the DataFile in the result sInput, so that should be fine using isTempPcaB to check.  I'd have to look more closely at how you've changed FilesB to sInputB though.  

By the way, if we don't keep the function compatible with both Files and sInput as inputs, I think at least there should be an explicit check and clear warning message of how this was changed, just to be safe. 

> It seems the L282 is broken when old PCA is requested

It works for me with PLV for example.  When exactly does it fail?

> At this moment, only the PCA scout function implies flattening before connectivity. Will this be the general approach for other scout functions?

I believe this is indeed what we decided following your tests, to have it as the general approach.  I just didn't consider it part of this PR's scope.  And we need to decide how to implement this: reject unconstrained inputs, or perform it from within the connectivity processes, and if the latter, whether or not to save the flattened files permanently in the tree.

2023-04-18 13:51 UTC, Moo-Marc commented on toolbox/process/functions/process_cohere2_2021.m
Needs to be reverted following bst_connectivity accepting sInputs.

2023-05-05 21:58 UTC, rcassani commented on toolbox/connectivity/bst_connectivity.m
> +end
Connectivity A×B: cases where flatten is required, but only FilesB are results need to be handled. 
Currently an error in `process_extract_scout>LoadFile` occurs.

2023-05-06 00:18 UTC, rcassani commented on toolbox/connectivity/bst_connectivity.m
> +end
@Moo-Marc, at first glance, this could be addressed as below. Although you may want to handle it in a different way
```
--- a/toolbox/process/functions/process_extract_scout.m
+++ b/toolbox/process/functions/process_extract_scout.m
@@ -590,6 +590,9 @@ function [isUnconstrained, nComponents] = CheckUnconstrained(sProcess, sInputs,
     isUnconstrained = [];
     nComponents = [];
     if nargin < 3 || isempty(sResults)
+        if ~strcmpi(sInputs(1).FileType, 'results')
+            return
+        end
         % Load first file, without data.
         sResults = LoadFile(sProcess, sInputs);
         if isempty(sResults)

```

2023-05-16 22:05 UTC, Moo-Marc commented on toolbox/connectivity/bst_connectivity.m
For posterity: we decided to add flattening with PCA, before scouts and connectivity, as an option independently of the scout function.

2023-05-26 20:06 UTC, rcassani commented on toolbox/connectivity/bst_connectivity.m
> +        OPTIONS.PcaOptions, FilesA, OPTIONS.TargetA, FilesB, OPTIONS.TargetB);
Produces error en case of `1xN`, with `1` = A channel of data, and `N` = N Scouts:

`Unexpected scout definition for running PCA with temporary files.` L1449 in process_extract_scout, as `AtlasListA` is not an Atlas but the channel name for files A.

2023-06-06 16:51 UTC, merged