Head points & manual registration figure
brainstorm-tools/brainstorm3 pull request #590
Opened 2022-11-18 22:58 UTC by Moo-Marc

As discussed in https://github.com/brainstorm-tools/brainstorm3/pull/567, this is an alternate fix to https://github.com/brainstorm-tools/brainstorm3/commit/422078ae45b6a2bf08352797218a812d55fc5f0b for head point coloring / colorbar behavior, where points are now registered as a figure surface.  
Additionally:

- Other minor fixes to colormaps/SetMaxCustom
- A "reset" button is added to the figure
- Some checks are made on previous registration steps (manual/auto) and printed to the command window.

Draft: that last point needs a fix, and I want to retest properly as I split this from another branch.

2022-11-21 11:03 UTC, ftadel commented
You asked me to work on these issues, I did it three days later. 
It took many hours of my work time, which is limited and quite packed.
I'm sorry, I'm not going to spend more time on this topic, for reviewing hundreds of lines of code that do something similar than what is already implemented in the master branch. 

If you need to add additional fixes, please build them on top of the current master branch.
Adding a new surface would have more side effects than what I proposed, I'm not in favor of it. Please do not open a PR that just projects this one on top of the current master branch.

Next time, please decide in advance if you want to work on something, or if you want me to work on it.
Don't do both as it is quite inefficient in terms of resource allocation.
If you are not sure what is the best approach, please ask me in advance, I'm easily available for short zoom meetings.

2022-11-21 14:58 UTC, Moo-Marc commented
> If you are not sure what is the best approach, please ask me in advance

Sorry this was a case of miscommunication.  I guess my request was a bit vague, asking for advice and leaving the door open to more assistance, because I didn't know if you'd have time to work on this.  I started working on it while waiting to hearing back and making other changes as I was using the manual registration.  From now on, let's please both indicate when we're working on something.  And I'll be clearer in my requests.

The reset button is to reset the registration, not the figure view parameters (double-click).  It basically is a shortcut to closing without saving and reopening the manual registration figure.  I find it useful since there's no undo, e.g. if I press the wrong mouse button and make a big registration change when I meant to rotate the view.

I'll remove the points-as-surface changes and reopen this PR when I've finished testing.  The three other points are still useful, including a bug fix to SetMaxCustom if there's more than one surface.

2022-11-22 21:13 UTC, Moo-Marc commented
I edited the initial post above to reflect the remaining changes in this PR.

The changes to panel_surface/GetSurface were to get the scalp surface specifically instead of the selected surface.  It seemed like a practical functionality to have - getting a surface by type.  If I missed a simpler way to do it, please let me know.

2022-11-23 18:16 UTC, ftadel reviewed
Looks good, just one little thing to check/fix.

2022-11-23 18:16 UTC, ftadel commented on toolbox/core/bst_colormaps.m
> +                        iSurfaces = find(strcmpi({TessInfo.ColormapType}, ColormapType));
Getting the surface with the appropriate colormap is good.
Using 'EEG', 'MEG' or 'NIRS' as DataType is good too.

However, in which case do you have multiple surfaces with the same ColormapType?
If you can't produce this: please remove the loop on iSurfaces and only use the first one.

2022-11-23 18:16 UTC, ftadel commented on toolbox/process/functions/process_adjust_coordinates.m
>  function varargout = process_adjust_coordinates(varargin)
I did not review these changes.

2022-11-23 18:16 UTC, ftadel commented on toolbox/sensors/channel_align_manual.m
> +process_adjust_coordinates('CheckPrevAdjustments', in_bst_channel(ChannelFile), sMri);
I did not check this.

2022-11-25 22:33 UTC, Moo-Marc commented on toolbox/core/bst_colormaps.m
> +                        iSurfaces = find(strcmpi({TessInfo.ColormapType}, ColormapType));
Done.

2022-11-27 15:35 UTC, ftadel requested changes

2022-11-27 15:35 UTC, ftadel commented on toolbox/process/functions/process_adjust_coordinates.m
> +                    iAlignRemoved = find(contains(ChannelMat.History(iAlign,3), 'AdjustedNative'), 1, 'last');
Contains was added in 2016b: must be removed.

2022-11-27 15:35 UTC, ftadel commented on toolbox/process/functions/process_adjust_coordinates.m
> +        iMriHist = find(strcmpi(sMri.History(:,3), 'Applied digitized anatomical fiducials'), 1, 'last');
Where is this defined?

2022-11-27 15:35 UTC, ftadel commented on toolbox/process/functions/process_adjust_coordinates.m
> +    end
Where is all this coming from?

2022-11-27 15:35 UTC, ftadel commented on toolbox/sensors/channel_align_manual.m
> +process_adjust_coordinates('CheckPrevAdjustments', in_bst_channel(ChannelFile), sMri);
I'm not sure I understand what is happening in this function.
I am not comfortable adding this here, as this is a very standard function.

If the idea is only to display the previous changes done on the file: you can simply right-click on the channel file > File > View history.

2022-11-28 17:08 UTC, Moo-Marc commented on toolbox/process/functions/process_adjust_coordinates.m
> +    end
removed

2022-11-29 10:24 UTC, ftadel approved these changes

2022-11-29 10:27 UTC, merged