Label and export NIRS channels
brainstorm-tools/brainstorm3 pull request #623
Opened 2023-05-24 01:00 UTC by Edouard2laire

2023-05-24 15:15 UTC, rcassani requested changes

2023-05-24 15:15 UTC, rcassani commented on toolbox/io/export_channel_nirs_atlas.m
> +isSelect = java_dialog('checkbox', 'Select information to export:', 'Compute contact labels', [], Columns(:,2), isSelect);
Update window title

2023-05-24 15:16 UTC, rcassani commented
@Edouard2laire, are there recommendations regarding the Radius to be used for NIRS channel labelling?

2023-05-24 18:18 UTC, Edouard2laire commented
ok. i applied your comments. Let me know if that looks ok for you :)




> @Edouard2laire, are there recommendations regarding the Radius to be used for NIRS channel labelling?

Unfortunately, up to my knowledge there is no recommendation. but I will try to check a bit more. From my tests, 3mm seems to make the more sense

2023-05-26 02:50 UTC, Edouard2laire commented on toolbox/io/export_channel_nirs_atlas.m
> +if (nargin < 5) || ismpety(isInteractive)
isempty instead of ismpety

2023-05-26 16:56 UTC, rcassani requested changes
Minimal changes, after that it should be ready to merge :)

2023-05-26 16:56 UTC, rcassani commented on toolbox/io/export_channel_nirs_atlas.m
> +end
This check should be just after getting the study, to avoid asking the user for a file that will not be created

2023-05-26 16:56 UTC, rcassani commented on toolbox/io/export_channel_nirs_atlas.m
> +end
Should not be the check for `isChanSelected`?

2023-05-26 18:27 UTC, Edouard2laire commented
Done. Thanks a lot for your comments :)

2023-06-02 14:56 UTC, Edouard2laire commented
hello.
do you think you would have time to merge this next week ? :)

2023-06-02 18:52 UTC, merged