Generation of thresholded mesh from CT
brainstorm-tools/brainstorm3 pull request #684
Opened 2024-02-19 19:13 UTC by chinmaychinara91

1. Assuming we have a CT by following [Import CT](https://neuroimage.usc.edu/brainstorm/Tutorials/ImportAnatomy#Import_CT)

2. Right-click on the **CT → MRI segmentation → Generate mesh from CT** . This will bring the **Generate isosurface** window. This window shows 3 things in the Hounsfield Unit, the Background level, the White level and the Set isoValue fields. The first and second values are calculated automatically from the histogram of the CT. This is to help the user to decide on what to set the isoValue for getting a good thresholded mesh. Another way is to refer to this https://en.wikipedia.org/wiki/Hounsfield_scale. The best way, however is to just open the CT in the MRI viewer browse through the electrode intensities and do trial and error to get the best value for a clean mesh. In this case, setting the value to **2400** gave a good result. Set the **isoValue** to **2400** and press **OK.** 

![Screenshot 2024-02-19 110722](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/d720129c-4bc0-44b7-95a4-e65040b4778b)

![Screenshot 2024-02-19 110645](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/516247ef-9780-4ab1-8279-f67b7bf94a98)

3. This will generate a isosurface which looks something like under. **THIS WILL HELP IN DOING SEEG ELECTRODE CONTACT LOCALIZATION**.
![Screenshot 2024-02-19 111047](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/54e48822-0a24-4ecf-a88a-1f292b2f7e64)

2024-02-21 21:32 UTC, rcassani requested changes
Overall the code looks good to me.
Few things to address.

2024-02-21 21:32 UTC, rcassani commented on toolbox/anatomy/tess_isosurface.m
> +                                {num2str(sMri.Histogram.bgLevel), num2str(sMri.Histogram.whiteLevel), num2str(1900)});
The first and second inputs are not used for now, right?
If they are not going to be used in the future, we should just print them instead of being a editable fields.

2024-02-21 21:32 UTC, rcassani commented on toolbox/anatomy/tess_isosurface.m
> +                                {num2str(sMri.Histogram.bgLevel), num2str(sMri.Histogram.whiteLevel), num2str(1900)});
I'm not familiar with CT data. 
Will this guess number (1900) change from CT to CT?
If so, we can we propose a better guess based on the CT data?

2024-02-21 21:32 UTC, rcassani commented on toolbox/anatomy/tess_isosurface.m
> +    isoValue = sMri.Histogram.whiteLevel;
Potential error, this overrides the input argument given to the function

2024-02-21 21:37 UTC, rcassani commented
@chinmaychinara91, check the review above.

There are few commits that I want to add on integration of CT now in Brainstorm, and I think this PR is a good place to put them so we take it as common place for further development in the sEEG contact location. What do you think?  

The two small modifications on `mri_coregister` added to this branch, as part of those modifications.

2024-02-21 22:11 UTC, chinmaychinara91 commented on toolbox/anatomy/tess_isosurface.m
> +                                {num2str(sMri.Histogram.bgLevel), num2str(sMri.Histogram.whiteLevel), num2str(1900)});
That is correct. Let me make these changes.

2024-02-21 22:14 UTC, chinmaychinara91 commented on toolbox/anatomy/tess_isosurface.m
> +                                {num2str(sMri.Histogram.bgLevel), num2str(sMri.Histogram.whiteLevel), num2str(1900)});
That was my thought as well. But from all the CT data I have encountered till now that seems to be a good number based on manual inspection as mentioned in the PR description above. For now let's keep it to 1900. But if we find any new ways to better initialize this value in the future will update it.

2024-02-21 22:38 UTC, chinmaychinara91 commented on toolbox/anatomy/tess_isosurface.m
> +    isoValue = sMri.Histogram.whiteLevel;
Yes thanks for catching this.

2024-02-21 22:47 UTC, chinmaychinara91 commented
@rcassani:

The `mri_coregister` changes look good. Others I will update.

2024-02-21 23:12 UTC, chinmaychinara91 commented
@rcassani updated with the requested changes.

2024-02-21 23:33 UTC, chinmaychinara91 commented
just found another issue. let me update it.

2024-02-21 23:53 UTC, chinmaychinara91 commented on toolbox/anatomy/tess_isosurface.m
> +                                {num2str(sMri.Histogram.bgLevel), num2str(sMri.Histogram.whiteLevel), num2str(1900)});
Check https://github.com/brainstorm-tools/brainstorm3/pull/684/commits/ea8777bffd01536a3559a3860c444237a1433900. Found a better way using `sMRI.Histogram.maxIntensity`.  Added a parameter check for that as well since anything above `sMRI.Histogram.maxIntensity` retunrs empty and there is nothing to compute.

2024-02-21 23:53 UTC, chinmaychinara91 commented
@rcassani done from my end.

2024-02-23 22:45 UTC, rcassani commented
I have updated the integration of CT data into Brainstorm: 
 * By creating its own node type we can handle better its behaviour, display and menus
 * The MRI menus that do not apply to CT have been removed
     * @tmedani, What do you think of the updated menu for CT? 
       Do we want to keep the 'MNI normalization' option for CT data? 
     
@chinmaychinara91, please test that I did not break anything with these changes.
To test the new node type the file:
1. The file `brainstorm3\java\brainstorm.jar` must be replaced with the one in this one: https://github.com/rcassani/bst-java/blob/add-ct/brainstorm/dist/brainstorm.jar
2. Matlab needs to be restarted as well

---
The title and description of this PR have been updated to match the contents

2024-02-23 23:13 UTC, tmedani commented
> I have updated the integration of CT data into Brainstorm:
> 
> * By creating its own node type we can handle better its behaviour, display and menus
> * The MRI menus that do not apply to CT have been removed
>   
>   * @tmedani, What do you think of the updated menu for CT?

I need to check the menu first for a complete feedback, 

>     Do we want to keep the 'MNI normalization' option for CT data?

I think we can keep it since it can be used in some other scenario, and it is always useful.

> The MRI 3D slices or,

Let's do it on the 3D MRI viewer, it has more significance.

2024-02-23 23:17 UTC, chinmaychinara91 commented on toolbox/anatomy/tess_isosurface.m
> +%         [Vertices, Faces]    = tess_isosurface(sMri,     isoValue=1900)
doing it now

2024-02-23 23:36 UTC, chinmaychinara91 commented
Also we both reviewed the changes they look great and work perfect.

2024-02-24 00:03 UTC, chinmaychinara91 commented on toolbox/tree/tree_callbacks.m
> +            case 'volct'
can we maybe merge `case 'volct'` with `case 'volatlas'` to `case {'volatlas', 'volct'}` as they are doing the same thing essentially ?

2024-02-26 14:00 UTC, rcassani commented on toolbox/tree/tree_callbacks.m
> +            case 'volct'
Sounds good. Done at [8810927](https://github.com/brainstorm-tools/brainstorm3/pull/684/commits/8810927dcdea4f047b1f5c49ee4e7cf46e2d664a)

2024-02-26 17:24 UTC, chinmaychinara91 commented
all things look good @rcassani. Just wrt https://github.com/brainstorm-tools/brainstorm3/pull/684#discussion_r1501248906, as you suggested and as @tmedani agreed, we can add loading of just the MRI 3D slices along with the new mesh so that we get a good reference for the contacts.

2024-02-26 20:29 UTC, chinmaychinara91 commented
> all things look good @rcassani. Just wrt [#684 (comment)](https://github.com/brainstorm-tools/brainstorm3/pull/684#discussion_r1501248906), as you suggested and as @tmedani agreed, we can add loading of just the MRI 3D slices along with the new mesh so that we get a good reference for the contacts.

Updated and added this.

2024-02-26 20:58 UTC, rcassani commented
Great, I'm merging this PR!
@chinmaychinara91, please update the "Generation of thresholded mesh from CT" in the PR description to match the final version

2024-02-26 21:00 UTC, rcassani approved these changes

2024-02-26 21:01 UTC, merged