Update panel ieeg: Add manual contact localization capabilities
brainstorm-tools/brainstorm3 pull request #689
Opened 2024-03-05 03:35 UTC by chinmaychinara91

**[THESE ARE USED AS TEST DATA BELOW](https://drive.google.com/drive/folders/1TI8wANAb09erddYP52bXyXo5xuajLCNf?usp=sharing)**

Steps:
1. Load the CT and generate isoSurface as per the steps in [this](https://github.com/brainstorm-tools/brainstorm3/pull/684)
2. Close all figure windows using the **X** button on the top right of the BST GUI making sure the cache is clear
3. Right click on the CT and click on **ECOG/SEEG implantation**
4. It opens the functional tab with the MRI with CT overlay loaded as one figure and the isoSurface with 3rd MRI view another figure. It also opens the **[panel_ieeg](https://neuroimage.usc.edu/brainstorm/Tutorials/Epileptogenicity#Panel_iEEG)** tab. 
![Screenshot 2024-03-04 185705](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/b9904995-047a-47dd-8377-6cb00283cd06)
5. Click the **+** icon from the Panel menu and add **panel_coordinates** as it will be used later.

**Updates in the Panel iEEG features and functionalities:**
1. Earlier user could set the tip and entry using just the MRI Viewer, but now this can be done from the 3D Viz's thresholded isosurface as well using the panel_coordinates which gives a much detailed level of accuracy of setting the points. 
- STEPS:
a. Make sure the MRI Viewer is the active window, ** Add an electrode** using the **+** sign.
b. Choose the **Model** from the bottom drop down list in the panel as required (can use **PMT 2102-16-091/2102-16-101**) for now.
c. Go to the **Coordinates** tab, click **Select** and choose the point in the iso surface which is going to be set as the tip. This should plot a yellow crosshair marker point on the blob. Then right click on the MRI Viewer to make it the active window, click on the electrode name created in the ieeg panel and at the bottom click **Set tip**. Choose **3DViz** from the pop up and the **Set tip** button turns green indicating the tip been set. **This point in 3D is at the centroid of the blob which gives a more accurate location of the contact**.
d. Go to the **Coordinates** tab again, click **Select** and choose the point in the iso surface which is going to be set as the entry point. This should plot a yellow crosshair marker point on the blob. Then right click on the MRI Viewer to make it the active window, click on the electrode name created in the ieeg panel and at the bottom click **Set skull entry**. Choose **3DViz** from the pop up and the **Set skull entry** button turns green indicating the tip been set.
e. The MriViewer gets updated with the an aligned electrode.
f. Click on **Contacts: Save Modifications**. And then double click the **SEEG/ECOG()** channel under **Implantation** node to update the 3DViz.

2. List of contacts added right next to the electrode list. Once a user click on the electrode it shows the list of contacts user to browse through.

3. Clicking on the contact in the list highlights the location on the MRI Viewer by taking the cross-hair there.

4. Clicking on the contact in 3D Viz highlights the  contact and electrode in Panel which in turn performs steps as in 3. above

5. Line fitting through the points by doing **Contacts: Line fit through contacts** is also added. This is helpful if suppose the user fine tunes the contacts by updating their location either by choosing the desired point in isosurface using the coordinates panel or directly choosing a point in MRI Viewer and then **Right clicking on the MRI VIewer, Electrodes: Set Electrode position**. If the user then clicks **Contacts: Line fit through contacts** this shows a rough trajectory of the actual path. THIS WILL BE REPLACED BY SPLINE FITTING LATER.

**Update in the panel_surface**
Once we have a isosurface with us we can now control the **Thresh** slider allows regenerating of isoSurface as required by the user in real time while localizing contacts there by giving more control for getting accurate contacts.

2024-03-05 03:36 UTC, chinmaychinara91 commented
@rcassani we can start discussing from here and then I will keep updating the details as required.

2024-03-05 08:53 UTC, chinmaychinara91 reviewed
@rcassani you can start reviewing from this point https://github.com/brainstorm-tools/brainstorm3/pull/689/commits/af31e7e27ce2b5c074dec51b2fe2857cfbac37e8 down as things prior to this are either merged to existing panel_ieeg or removed.

2024-03-14 19:35 UTC, chinmaychinara91 commented
Verified that nothing breaks for the [ECoG tutorial](https://neuroimage.usc.edu/brainstorm/Tutorials/ECoG) as well.

2024-03-20 14:43 UTC, rcassani requested changes
The code in the PR looks good. There are some points that need to be addressed, see the comments.

---

There is also this strange behaviour: 

0. Close all figures
1. Double-click on channel file
2. Add Coordinates panel
3. Back to iEEG panel, add new SEEG electrode
4. On Coordinates panel, select 'Select' option.
5. Click-on iso surface. This opens the MRI viewer

Bug: The values in the Coordinates panel appear for an instant, then they are removed. Although the + marker is shown), until I click again in the same place.

6. Go back to iEEG panel, click on "Set tip"
Bug2: Error: MRI viewer must be open

2024-03-20 14:54 UTC, rcassani commented on toolbox/gui/figure_mri.m
@chinmaychinara91, this comment is not outdated. It refers to the proposed changes in `figure_mri`

2024-03-20 14:54 UTC, rcassani commented on toolbox/io/in_channel_curry_pom.m
@chinmaychinara91, this comments is also not outdated

2024-03-20 16:35 UTC, chinmaychinara91 commented
> The code in the PR looks good. There are some points that need to be addressed, see the comments.
> 
> There is also this strange behaviour:
> 
> 0. Close all figures
> 1. Double-click on channel file
> 2. Add Coordinates panel
> 3. Back to iEEG panel, add new SEEG electrode
> 4. On Coordinates panel, select 'Select' option.
> 5. Click-on iso surface. This opens the MRI viewer
> 
> Bug: The values in the Coordinates panel appear for an instant, then they are removed. Although the + marker is shown), until I click again in the same place.
> 
> 6. Go back to iEEG panel, click on "Set tip"
>    Bug2: Error: MRI viewer must be open


Bug1 is not a bug actually. It was a part of the original code. It happens because when the panel coordinates is not in focus, the `RemoveSelection()` is called. Maybe we want to change it ?

Bug2: Let me look into it.

2024-03-20 18:01 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
sounds good. Your solution works perfect.

2024-03-20 18:15 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +        listModel.addElement(sprintf('%s   %3.1f   %3.1f   %3.1f', string(sContactsName(i)), sContacts(:,i).*1000));
I think a 3.2 precision is better. 3.1 rounds it up too much. suggested change 12e1459e.

2024-03-20 19:00 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +    selData = regexp(selData, '   ', 'split');
correct. updated in 289a51c6.

2024-03-20 19:05 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
i feel the size of the spheres are too big if reduced by 2 as the isosurface blobs get covered by them. hence reduced it 4 times.

2024-03-20 19:13 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +function HighlightLocCont() %#ok<DEFNU>
The marker is just a tool to help get the desired point.  However we can add the feature that if open, the contact gets highlighted in the 3D window as well. Will work on it after resolving the rest of the comments.

Currently however, on selecting the 3D contact in 3DViz, the panel and MRI Viewer do get updated.

2024-03-20 19:15 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +                jPanelElecList.add(jCoordSys, BorderLayout.NORTH);
We can keep it for fine tuning later.

2024-03-20 19:26 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +        listModel.addElement(sprintf('%s   %3.1f   %3.1f   %3.1f', string(sContactsName(i)), sContacts(:,i).*1000));
Check that the text for the contact coordinates are not scaled like all the other items in the GUI. 

![image](https://github.com/brainstorm-tools/brainstorm3/assets/8238803/0f7ec5ec-1970-49e1-8a7f-2e392a6b3ce9)

2024-03-20 19:26 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
@tmedani any opinion on this display option?

2024-03-20 19:28 UTC, chinmaychinara91 commented on toolbox/tree/tree_callbacks.m
> +                        panel_ieeg('DisplayIsosurface', sSubject, hFig);
yes working on it.

2024-03-20 19:29 UTC, rcassani commented on toolbox/gui/panel_surface.m
True, if the threshold is different for different electrode localization, yes, it should be possible to redo it quickly. But I don't think a slider just for this case is the option. Maybe the slider could be hidden for all the other types of surfaces

@tmedani, can you think in a better approach?

2024-03-20 19:29 UTC, chinmaychinara91 commented on toolbox/tree/tree_callbacks.m
>                      elseif strcmpi(DisplayMod{1}, 'SEEG')
yes working on it.

2024-03-20 19:30 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +        listModel.addElement(sprintf('%s   %3.1f   %3.1f   %3.1f', string(sContactsName(i)), sContacts(:,i).*1000));
Aah yes let me update that.

2024-03-20 19:41 UTC, chinmaychinara91 commented on toolbox/tree/tree_callbacks.m
> +                        panel_ieeg('DisplayIsosurface', sSubject, hFig);
updated 0a518800.

2024-03-20 20:14 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +        listModel.addElement(sprintf('%s   %3.1f   %3.1f   %3.1f', string(sContactsName(i)), sContacts(:,i).*1000));
check [41f127d](https://github.com/brainstorm-tools/brainstorm3/pull/689/commits/41f127d7a7ade9a3172647d5ead19a26f5da179f)

2024-03-20 20:17 UTC, chinmaychinara91 commented on toolbox/tree/tree_callbacks.m
> +                        panel_ieeg('DisplayIsosurface', sSubject, hFig);
check 0a518800

2024-03-20 21:01 UTC, tmedani commented on toolbox/gui/panel_surface.m
> True, if the threshold is different for different electrode localization, yes, it should be possible to redo it quickly. But I don't think a slider just for this case is the option. Maybe the slider could be hidden for all the other types of surfaces
> 
> @tmedani, can you think in a better approach?

Having this slider for just the threshold is not optimized, indeed, and I believe we highlighted this previously, but we didn't find a better place for it.  Can we make it visible only for this application?
Otherwise within the figure as Ray proposed it.

2024-03-20 21:05 UTC, tmedani commented on toolbox/gui/panel_ieeg.m
> +        sMod(1).ElecLength    = 0.016;
> In fact, the line that is fit to the electrodes would be the equivalent to the **Total Exploration Length**


> It makes sense. You can make the changes what you feel is right. Having a length that would have all the contacts clearly visible would be for sure good. What do you think @tmedani ?

I agree with Ray here, this is much better

2024-03-20 21:09 UTC, tmedani commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
> i feel the size of the spheres are too big if reduced by 2 as the isosurface blobs get covered by them. hence reduced it 4 times.

i feel the size of the **spheres**  
do you mean the contact or the sphere, this is not clear to me. 

is ctSize the size of the contact or the isosurface?
i would keep the current size of the contact as it is without changing it.

2024-03-20 21:13 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
these are the spheres that is generated when user clicks "View contact as spheres" in panel ieeg.

reduce by 2 gives this:
![Screenshot 2024-03-20 141317](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/6bbb48d7-ecca-4122-99da-6cd8493d67bf)

reduce by 4 gives this:
![Screenshot 2024-03-20 141252](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/c117db69-7459-4032-96e2-758fa20ae8b9)

2024-03-20 21:21 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
@chinmaychinara91, can you create such plots with the same POV, and overleaping (with transparency) the view of "Display contactas as SEEG electrodes..."? 
(The overlapping with transparency should be easier to create with an image editing software)

2024-03-20 21:23 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
@tmedani, the variable `ctSize` corresponds to the radius of the sphere to plot. As such using `ctSize` of half the length, makes the sphere to have the same diameters as the contact length, thus spacing between spheres is the same as the space between contacts

2024-03-20 21:29 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
> @tmedani, the variable `ctSize` corresponds to the radius of the sphere to plot. As such using `ctSize` of half the length, makes the sphere to have the same diameters as the contact length, thus spacing between spheres is the same as the space between contacts

Oh I did not know that was the reason. I always thought it was just for visualization. If this is the case then we should keep it at reduce by 2 as is. It makes complete sense now. Maybe we can add this comment above the `ctSize` with the explanation above.

2024-03-20 21:35 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
updated eba54925.

2024-03-20 21:35 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
Yes, it is only for visualization, to me it makes more sense to use a sphere that the same size as the contact. 

The best solution though is to use the same approach as with the connectivity graph, and have the sphere scaling as and option in the figure: 
https://neuroimage.usc.edu/brainstorm/Tutorials/ConnectivityGraph#Display_options

![image](https://github.com/brainstorm-tools/brainstorm3/assets/8238803/8faea0aa-4d8b-459c-b98c-fdff2738f7a1)

2024-03-20 21:40 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +                    ctSize = [1 1 1] .* sElec.ContactLength ./ 4;
this sounds good as well. I will fine tune with this feature later.

2024-03-20 21:46 UTC, rcassani commented on toolbox/io/in_channel_curry_pom.m
Already in master as [a2faeda](https://github.com/brainstorm-tools/brainstorm3/commit/a2faeda3ff3530889fb701b1008fc7fea081fcbf)

2024-03-20 21:48 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +function HighlightLocCont() %#ok<DEFNU>
Yes, it would be good to have this feature.

Otherwise, it feels strange that the MRIviewer and the 3D figure are synch only for some actions

2024-03-20 21:54 UTC, rcassani commented
> Bug1 is not a bug actually. It was a part of the original code. It happens because when the panel coordinates is not in focus, the RemoveSelection() is called. Maybe we want to change it ?

A quick fix would be to return the 3DFig to be the current figure after the MRIviewer is opened

2024-03-20 22:02 UTC, rcassani commented on toolbox/gui/panel_surface.m
Another point against the slider is that it does not allow fine tuning. The step in the GUI depends on the pixel length of the slider in the case below each step is around 40 units.

2024-03-21 02:59 UTC, chinmaychinara91 commented
> > The code in the PR looks good. There are some points that need to be addressed, see the comments.
> > There is also this strange behaviour:
> > 
> > 0. Close all figures
> > 1. Double-click on channel file
> > 2. Add Coordinates panel
> > 3. Back to iEEG panel, add new SEEG electrode
> > 4. On Coordinates panel, select 'Select' option.
> > 5. Click-on iso surface. This opens the MRI viewer
> > 
> > Bug: The values in the Coordinates panel appear for an instant, then they are removed. Although the + marker is shown), until I click again in the same place.
> > 
> > 6. Go back to iEEG panel, click on "Set tip"
> >    Bug2: Error: MRI viewer must be open
> 
> Bug1 is not a bug actually. It was a part of the original code. It happens because when the panel coordinates is not in focus, the `RemoveSelection()` is called. Maybe we want to change it ?
> 
> Bug2: Let me look into it.

Bug1 solved: check 76e9a115

2024-03-21 03:03 UTC, chinmaychinara91 commented
> Bug1 is not a bug actually. It was a part of the original code. It happens because when the panel coordinates is not in focus, the `RemoveSelection()` is called. Maybe we want to change it ?

Solved: check 76e9a115

2024-03-21 03:34 UTC, chinmaychinara91 commented
> > 6. Go back to iEEG panel, click on "Set tip"
> >    Bug2: Error: MRI viewer must be open

solved check f4580227

2024-03-21 03:40 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +        sMod(1).ElecLength    = 0.016;
check 75eca4d0.

2024-03-21 05:00 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +function HighlightLocCont() %#ok<DEFNU>
updated 27f4ce07.

2024-03-21 17:39 UTC, rcassani commented on toolbox/tree/tree_callbacks.m
> +                        panel_ieeg('DisplayIsosurface', sSubject, hFig);
This behaviour has been moved to `view_channels_3d` in [34fbf52](https://github.com/brainstorm-tools/brainstorm3/pull/689/commits/34fbf522d9a4eda787f70357c42ee90b35b780b8)

2024-03-21 17:43 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +function HighlightLocCont() %#ok<DEFNU>
Nice addition

2024-03-21 17:43 UTC, rcassani commented on toolbox/tree/tree_callbacks.m
>                      elseif strcmpi(DisplayMod{1}, 'SEEG')
Handled now in [34fbf52](https://github.com/brainstorm-tools/brainstorm3/pull/689/commits/34fbf522d9a4eda787f70357c42ee90b35b780b8)

2024-03-21 17:46 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> +                jPanelElecList.add(jCoordSys, BorderLayout.NORTH);
added [64bd9a4](https://github.com/brainstorm-tools/brainstorm3/pull/689/commits/64bd9a4e1f5a97938e3fd1def1913ce8dc3559d3)

2024-03-21 17:51 UTC, chinmaychinara91 commented
@rcassani I guess all the things are done except the isosurface which I will come to a solution based on our above discussion and wrap it up today.

2024-03-21 21:29 UTC, chinmaychinara91 commented
@rcassani @tmedani Do you think https://github.com/brainstorm-tools/brainstorm3/pull/689/commits/c2c9ab33a5d8448f8ebe807c9213ecb2b53bbe7d would be a good feature to have ? When a user clicks on a contact in the panel the camera moves to show the contact in 3D.

![move](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/d3b4c2fb-04d3-4629-a3c5-80a92128edd8)

2024-03-21 21:48 UTC, rcassani commented
Not a big fan of the auto camera, at least not without an option to turn it off

2024-03-21 21:49 UTC, chinmaychinara91 commented
> Not a big fan of the auto camera, at least not without an option to turn it off

ok I will revert it then

2024-03-21 22:16 UTC, rcassani commented on toolbox/gui/panel_surface.m
Commit [0f949f2](https://github.com/brainstorm-tools/brainstorm3/pull/689/commits/0f949f2d0149562448f855cf6e9539ac4d3fb7f6) complete hides the isosurface threshold slider and labels.

This is a temporary solution as an empty space is still there for other surfaces.

We need to thing in a better option, to be able to adjust the threshold without creating a new file every time. An inspiration example is how [manual MRI-sensor registration](https://neuroimage.usc.edu/brainstorm/Tutorials/ChannelFile#Manual_registration) is performed: the user can interact with the window until they are satisfied.

2024-03-21 22:20 UTC, chinmaychinara91 commented on toolbox/gui/panel_surface.m
@rcassani that sounds perfect. Thank you.

2024-03-25 18:14 UTC, rcassani approved these changes

2024-03-25 18:15 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +    end
Do we need these callbacks for contacts?

2024-03-25 19:14 UTC, merged