[panel ieeg bugfix] For backward compatibility with old tutorials
brainstorm-tools/brainstorm3 pull request #700
Opened 2024-04-24 05:58 UTC by chinmaychinara91

**Issues with [Epileptogenicity](https://neuroimage.usc.edu/brainstorm/Tutorials/Epileptogenicity) tutorial:**
1. In sections SEEG timeseries and 2D topography, viewing 2D Electrodes and 3D electrodes raises an error. 
![Screenshot 2024-04-23 155838](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/a5cbb2c1-4d1c-4db0-90e1-f19a3458178b)
Reason: `GetElectrodes()` in `panel_ieeg` looks for MRI Viewer for getting the electrode details but is not able to find.
**Fix:** https://github.com/brainstorm-tools/brainstorm3/commit/73f7a1fff6442e5b2f4b98159c3e9710bfec4fe8 https://github.com/brainstorm-tools/brainstorm3/commit/a151ca3cfda90cad672356a1c1705c19eefb4512 https://github.com/brainstorm-tools/brainstorm3/commit/0faaa2f28cff999af28f9819c6c237776d59e718

**General issues**
1. Closing MRI Viewer closes all other figures using the [X] button on the top
**Fix:** https://github.com/brainstorm-tools/brainstorm3/commit/88c1d7321ffeac1113fa015bce5af7c9f649cced

2024-04-24 05:58 UTC, chinmaychinara91 commented
@rcassani don't review it yet. Will let you know once it is ready.

2024-04-24 10:50 UTC, rcassani commented
@chinmaychinara91, if it is a work in progress make a it Draft.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft

2024-04-24 17:38 UTC, chinmaychinara91 commented
I verified both the tutorials [ECoG ](https://neuroimage.usc.edu/brainstorm/Tutorials/ECoG)and [Epileptogenicity ](https://neuroimage.usc.edu/brainstorm/Tutorials/Epileptogenicity) for backward compatibility. Except the issues listed above everything looks good. 

You can review it now.

2024-04-24 22:10 UTC, rcassani requested changes

2024-04-24 22:10 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +end
Is it possible to call the function from `figure_mri` or the call this function in `figure_mri` to avoid duplicating code? The type of the caller figure can be obtained from with `hFig`

Maybe placing it panel_ieeg?

2024-04-24 22:10 UTC, rcassani commented on toolbox/gui/figure_3d.m
> -
To revert

2024-04-24 23:04 UTC, chinmaychinara91 commented on toolbox/gui/figure_3d.m
> +end
I think we can have it in panel_ieeg. That will make more sense. Let me work on it.

2024-04-24 23:39 UTC, chinmaychinara91 commented on toolbox/gui/figure_3d.m
> +end
Check https://github.com/brainstorm-tools/brainstorm3/pull/700/commits/2afeed0f5b090d224086ec0a1eaacbcf7644ac8e

2024-04-25 13:26 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +end
Looks good. Test it thoughtfully and it should be ready to be merged.

2024-04-25 13:27 UTC, rcassani approved these changes

2024-04-25 17:33 UTC, rcassani commented on toolbox/gui/figure_3d.m
> +end
@chinmaychinara91, let me know when you are done with tests to merge

2024-04-25 18:05 UTC, chinmaychinara91 commented on toolbox/gui/figure_3d.m
> +end
yes. I am running some tests will let you know.

2024-04-25 18:42 UTC, chinmaychinara91 commented on toolbox/gui/figure_3d.m
> +end
You can merge now.

2024-04-25 21:02 UTC, merged