Automatic EEG localization and labelling using Revopoint 3D and Brainstorm
brainstorm-tools/brainstorm3 pull request #716
Opened 2024-06-28 21:28 UTC by chinmaychinara91

Goal is to allow automatic localization and labelling of EEG caps using 3D scanned mesh of a person wearing the cap (captured using [Revopoint 3D](https://www.revopoint3d.com/products/handheld-3d-scanner-range)). This represents a new low-cost, fast, easy-to-use approach for digitizing heads and electrodes as compared to the traditional [digitizer](https://neuroimage.usc.edu/brainstorm/Tutorials/TutDigitize).

Proposed GUI within Brainstorm:
![Screenshot 2024-06-28 142400](https://github.com/brainstorm-tools/brainstorm3/assets/21283733/3bec8a61-ed74-47c6-a67d-755cc1310e1f)

2024-07-23 16:20 UTC, rcassani requested changes
Please test exhaustively against legacy code in Brainstorm: tutorials in GUI and tutorial scripts.

The proposed changes are not compatible with what is currently in Brainstorm. They produce errors in fundamental functions such as `import_anatomy_fs.m` and potentially all the others `import_anatomy_*.m` scripts since all surfaces have `Color` field:

---
Error stack:
```
Line 159: Index in position 1 exceeds array bounds.

Call stack: 
>tess_downsize.m at 159 
>import_anatomy_fs.m at 312 
>process_import_anatomy.m>Run at 182 
>process_import_anatomy.m at 24 
>bst_process.m>Run at 236 
>bst_process.m>CallProcess at 2316 
>bst_process.m at 38
```

2024-07-23 16:20 UTC, rcassani commented on toolbox/db/db_template.m
Do we want to add this field to the template?
Can we save on the `.mat` file and only read it when needed?

2024-07-23 16:20 UTC, rcassani commented on toolbox/io/import_surfaces.m
> +        if isfield(NewTess, 'Color')
Since `NewTess` is created with `db_template('surfacemat')` it will always have the `Color` field, thus all surfaces are imported as `tess_textured_*.mat`

2024-07-23 16:38 UTC, chinmaychinara91 commented
> tutorials in GUI and tutorial scripts

Can you point me to this ?

2024-07-23 16:38 UTC, chinmaychinara91 commented on toolbox/db/db_template.m
I think yes it will be better to save it to the mat file rather than the template. Let me work on that.

2024-07-23 17:10 UTC, rcassani commented
> Can you point me to this ?


@chinmaychinara91 

### 1. Running tutorials on GUI
There are many tutorials in this page, that you can follow to verify the changes are backwards compatible
https://neuroimage.usc.edu/brainstorm/Tutorials/

### 2. Running tutorials with scripts
Most tutorials can be run with scripts, located in main Brainstorm repository. Look for the `tutorial_*.m` scripts:
https://github.com/brainstorm-tools/brainstorm3/tree/master/toolbox/script

There is also this private repo: https://github.com/brainstorm-tools/bst-tests

2024-07-23 20:08 UTC, chinmaychinara91 commented on toolbox/db/db_template.m
check [ced72dd](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/ced72ddafea0acc67a0b75d9752f600df3daf32d)

2024-07-23 20:09 UTC, chinmaychinara91 commented on toolbox/io/import_surfaces.m
> +        if isfield(NewTess, 'Color')
This should now work fine after [d7fbfcc](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/d7fbfcc2dd41749cffc031a3b60db71ad932e9f1) [ced72dd](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/ced72ddafea0acc67a0b75d9752f600df3daf32d)

2024-07-25 21:46 UTC, rcassani commented
Hey guys, unfortunately, we do not have a revopoint yet. 
Can you provide the following to tests the code in the PR?

* Some raw files to test the import of the new surface format
* A protocol where the sensor localization has been already performed

In addition, have you had the chance to run the digitization with Polhemus, to see that everything is fine with that?

2024-07-25 22:17 UTC, chinmaychinara91 commented
> Hey guys, unfortunately, we do not have a revopoint yet. Can you provide the following to tests the code in the PR?
> 
> * Some raw files to test the import of the new surface format
> * A protocol where the sensor localization has been already performed
> 
> In addition, have you had the chance to run the digitization with Polhemus, to see that everything is fine with that?

@rcassani: 

1. Based on the tutorial in the description above, raw test data is attached [here] (https://drive.google.com/drive/folders/1n9IlcMljsEiOjcED6KRxKH3k4nMT8WAN?usp=sharing) as **sub1_Waveguard_ANT_65.zip**
2. The test protocol can also be found in the link above as **TutorialDigitizer.zip**

I ran it in the simulated mode without the Polhemus connected. Functionalities looked good and nothing broke. Polhemus here at USC has gone for some repair. Once it is back I will check it.

Also ran the exhaustive testing with various tutorials as you instructed above. All looked good.

2024-07-25 22:23 UTC, tmedani commented
> In addition, have you had the chance to run the digitization with Polhemus, to see that everything is fine with that?

we can test that at USC, we have the digitizer around.

but if I understand it, this will not be an issue since the Digitizer simulation was working fine.

2024-07-25 22:33 UTC, rcassani commented
@chinmaychinara91, thank you for the data

> but if I understand it, this will not be an issue since the Digitizer simulation was working fine.

Correct, it should not be an issue. Though we must test it before merging the PR

2024-07-25 22:34 UTC, chinmaychinara91 commented
> @chinmaychinara91, thank you for the data
> 
> > but if I understand it, this will not be an issue since the Digitizer simulation was working fine.
> 
> Correct, it should not be an issue. Though we must test it before merging the PR

Yes definitely. We will test it here and let you know.

2024-07-25 22:35 UTC, tmedani commented
> > @chinmaychinara91, thank you for the data
> > > but if I understand it, this will not be an issue since the Digitizer simulation was working fine.
> > 
> > 
> > Correct, it should not be an issue. Though we must test it before merging the PR
> 
> Yes definitely. We will test it here and let you know.

It may require some time to do that on the digitizer itself. 
we need to set it up and run it.

2024-07-25 22:37 UTC, rcassani commented
@Moo-Marc, can you give us a hand with the test with the Polhemus?

2024-07-26 17:33 UTC, chinmaychinara91 commented
> > > @chinmaychinara91, thank you for the data
> > > > but if I understand it, this will not be an issue since the Digitizer simulation was working fine.
> > > 
> > > 
> > > Correct, it should not be an issue. Though we must test it before merging the PR
> > 
> > 
> > Yes definitely. We will test it here and let you know.
> 
> It may require some time to do that on the digitizer itself. we need to set it up and run it.

2024-07-26 17:34 UTC, chinmaychinara91 commented
> It may require some time to do that on the digitizer itself.
> we need to set it up and run it.

Will be testing the PR with Polhemus today. Will keep posted.

2024-07-28 19:34 UTC, chinmaychinara91 commented
The Polhemus here at USC is being but of a task as it just got back from repairs. @Moo-Marc could you help us in testing this PR out at your end ? Just want to make sure already available functionalities do not break.

2024-08-06 17:59 UTC, chinmaychinara91 commented
@Moo-Marc thank you so much. Do let me know once you test it out.

2024-08-19 21:39 UTC, chinmaychinara91 commented
[d753abd](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/d753abdd514b0d77c69aa1963ff10849dc2bd861) commit takes into account that the New Digitize Panel changes (https://github.com/brainstorm-tools/brainstorm3/pull/682) are merged to this PR.

2024-08-28 16:09 UTC, chinmaychinara91 commented
@rcassani this is ready for review. Both the legacy and new panel support Revopoint now. Do test it out on your end based on the tutorial in description and let me know if you face any issues.

2024-09-11 22:39 UTC, rcassani reviewed
@chinmaychinara91, @tmedani 
## General comments

The code works with the provided data, and following the steps in the tutorial. I have pushed commits to improve and fix bugs.

There is not a clear workflow for the case where the subject has its own anatomy. Indeed, the code is hard-coded to use the first available anatomy template.

@chinmaychinara91, I'm tagging you in some of the commits I pushed to indicate why they were done, to use similar approaches to improve your code.

### Panel digitize

* It seems there is no reason to have a different name for the panel
  See commits: c857f3e and 8d6bc3bd

### Automated detection of electrodes. 

* There are many places where values are hard-coded and will not work with `.obj` with different resolutions or with different caps.

* The code in the warpping section is not properly commented. It only works for two caps. It is not scalable. And it relies hundreds of lines copy-pasted lines of code. This makes it hard to review, and will make maintaining and extending a nightmare.

### Other comments
* Most comments in Brainstorm start with capitals, please follow that

2024-09-11 22:39 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        centerssketch = max(min(centerssketch,512-15),15);
These hard-coded values, where are they coming from?

2024-09-11 22:39 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        cap_pts = ([Ozx,Ozy;T8x,T8y;GNDx,GNDy;T7x,T7y]+1)*256;
This is inefficient and unnecessary.
Only one call to `bst_project_2d` is needed

2024-09-11 22:39 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        end
This just sorts the coordinates, use indexing instead of doing unnecessary FOR loops

2024-09-11 22:42 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +    % Fix old structure (bef 2024) for Digitize.Options.Montages
@chinmaychinara91, if adding new things into the well defined structures (in this case `bst_get('DigitizeOptions')`, you MUST support older versiong

2024-09-11 22:44 UTC, rcassani commented on toolbox/gui/view_surface_matrix.m
> +GlobalData.Surface(end) = sLoadedSurf;
@chinmaychinara91, this caused almost-empty entries in `GlobalData.Surface`, which cause a lot of warning in the Matlab console window when clearing the memory. 

Did you notice it?

2024-09-11 22:45 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        warp = tpsGetWarp(lambda, centerssketch(vec_atlas_pts,1)', centerssketch(vec_atlas_pts,2)', centerscap(ind,1)', centerscap(ind,2)' );
@chinmaychinara91, why to store those variables?

2024-09-11 22:47 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> -            sSubject = bst_get('Subject', Digitize.SubjectName);
@chinmaychinara91 Do not query the DB if there is not a real reason to do it.
When we move to the SQLite version, these calls will be slower

2024-09-12 17:00 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +    [NewTessMat.Faces, NewTessMat.Vertices] = reducepatch(TessMat.Faces, TessMat.Vertices, dsFactor);
@rcassani what would you recommend here then ? We observed this while testing before as well. One way I am thinking is maybe we can use reduce patch for maybe say 200 points and then out of those just select 100 points by filtering out the points detected in the edges.

2024-09-12 17:01 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +            surfaceFile = sSubject.Surface(iSurface(end)).FileName;
Good point. We should let the user select. Will make the change.

2024-09-12 17:02 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
Will have these fixed.

2024-09-12 17:03 UTC, chinmaychinara91 commented on defaults/eeg/Colin27/channel_ANT_Waveguard_65.mat
We just added it for testing in Colin27 anatomy. Will work it out with @tmedani to decide on how to distribute.

2024-09-12 17:05 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +        end
This was bugging me as well when I wrote it as well. I will handle it better. Let me work on it.

2024-09-12 17:07 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +        [centers, radii, metric] = imfindcircles(vc_sq,[1 25]); % 65 ANT waveguard
We did some testing and faced this issue of the range. I agree on what you say. Since for now we have a very limited set of caps, we need to more rigorous testing to get a good range.

2024-09-12 17:09 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +TessMat.Vertices = vertices ./ 1000;
That is correct. @yashvakilna had this in his version and it did not strike it then. This conversion is not required.

2024-09-12 17:11 UTC, chinmaychinara91 commented on toolbox/gui/view_surface_matrix.m
> +GlobalData.Surface(end) = sLoadedSurf;
I was getting them as well but could not get the root cause. Thanks for this.

2024-09-12 17:12 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +        warp = tpsGetWarp(lambda, centerssketch(vec_atlas_pts,1)', centerssketch(vec_atlas_pts,2)', centerscap(ind,1)', centerscap(ind,2)' );
Yuu men the `L,LnInv,bendE` ? They are not required. I forgot to remove them.

2024-09-12 17:29 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +            db_set_template(iSubject, sTemplates(1), 1);
I have confusion here. Doesn't the `Digitizer` use the same default anatomy approach as well ? We just drilled down the same logic for this now. But this is a good point as well. Also, how do we handle things for the `Digitizer` if the subject has a individual anatomy ?

2024-09-12 17:30 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +        centerssketch = max(min(centerssketch,512-15),15);
I will double check and get back.

2024-09-12 17:35 UTC, chinmaychinara91 commented
@rcassani thank you for your comments. I have replied to them individually. Do go through them. But to summarize yes it needs another round of cleanup from my end which I will work on this week. Definitely it is not generalized well and there are some hard coded values but we are yet to receive more samples with variety of caps to get a good sense of generalizing them.

2024-09-12 20:35 UTC, rcassani commented
@chinmaychinara91, related to [53f43dd](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/53f43dde11cbd2ea28e7a2bb0477bdac0fa7e7d8). 

Do not patch code just to make it work. 
You have to understand why there was a problem, and how it can be solved from origin. 

Moreover, remember to keep previous behaviours otherwise: 

* All the calls must be updated. E.g. the proposed changes brakes the calls `brainstorm digitize`
https://github.com/brainstorm-tools/brainstorm3/blob/23b805bea0cecaa09ef41de416fd95b8e65176b1/brainstorm.m#L141

* If user's code rely on this they will need to change their codes.

In addition, it would need to update the usage strings for `panel_digitize` and `panel_digitize_2024`

What about solving the bug from root like below?
This solution is compatible with former ways using 'Start' with `panel_digitize` and `panel_digitize_2024`

```
--- a/toolbox/sensors/panel_digitize.m
+++ b/toolbox/sensors/panel_digitize.m
@@ -40,7 +40,7 @@ end
 %#function icinterface
 
 %% ===== START =====
-function Start(DigitizerType) %#ok<DEFNU>
+function Start(varargin) %#ok<DEFNU>
     global Digitize    
     % ===== INITIALIZE CONNECTION =====
     % Intialize global variable
@@ -68,10 +68,11 @@ function Start(DigitizerType) %#ok<DEFNU>
             'trans',    []));
     
     % ===== PARSE INPUT =====
-    Digitize.Type = 'Digitize';
-    if nargin > 0 && ~isempty(DigitizerType)
-        Digitize.Type = DigitizerType;
+    DigitizerType = 'Digitize';
+    if nargin > 0 && ~isempty(varargin{1})
+        DigitizerType = varargin{1};
     end
+    Digitize.Type = DigitizerType;
     switch DigitizerType
         case 'Digitize'
             % Do nothing
```

Same thing must be done for `panel_digitize_2024`

2024-09-17 13:55 UTC, tmedani commented on defaults/eeg/Colin27/channel_ANT_Waveguard_65.mat
@chinmaychinara91  here

2024-09-19 01:09 UTC, chinmaychinara91 commented on toolbox/gui/view_headpoints.m
@rcassani This seems to be not working:

Steps for new panel:
1. Start Digitize->Digitizer
2. Click on collect point 3 times to get NAS, LPA, RPA

ERROR IS THROWN. **Unable to find hFig**

2024-09-19 11:46 UTC, rcassani commented on toolbox/gui/view_headpoints.m
If digitization was done previously with 3DScanner (`Digitize.Type = '3DScanner'`), right-click on channel file > Digitized head points > View head points failed.

It should be properly addressed now in 70992eeb

2024-09-24 21:41 UTC, chinmaychinara91 commented
@rcassani 

I have made all the changes based on the comments and discussions above. Let me know if you find any errors on your side.

To summarize:
1. User can now just right click on the imported texture surface > **Digitize (3D Scanner)** to start the digitization.
1. Regarding **There is not a clear workflow for the case where the subject has its own anatomy**, 
the user can right click on the subject > **Import surfaces** and import the textured surface. Then right click on the imported  textured surface > **Digitize (3D Scanner)** to start the digitization.follow step 1 above.
1. User now gets to choose what to do when starting 3D Scanner digitization (Use existing surface or Add a new surface).
1. Better way of sampling without having to use `reducepath`.
1. `auto_3dscanner` now handles all the automatic detection and labelling of 3D Scanner acquired mesh. For new caps, we just need to change the `getEegCapLandmarkLabels` function and that should be it.
1. Did some rigorous testing and was able to come up with a single range for  `imfindcircles` with the caps we have available. Check https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/3403c9ef4359220ca9b189425b14ea901ef3f079.
1. Updated the cap templates for Colin27 and ICBM152. Check https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/c49ebc6cc474979bfd634731f5be67dcca33e6bc.
1. The textured surface in database is updated with `Digitize.Transf` transformation once the fiducials are digitized.
1. Had forgot about this https://forum.revopoint3d.com/t/revopoint-generated-mesh-coordinate-system/25662. The Revopoint vertices are in 'mm'. Did some digging here https://www.fieldtriptoolbox.org/tutorial/electrode/ and I think we need this approach https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/b1124bf6e0fc558fd81ffb303ff36d0c4210859d if we want to support any generic head surface acquired through other devices. 
1. Needed to do some ordering changes in the way the initialization points were captured for scalability. 

Will update the tutorial to match the changes for you to test.

2024-09-25 20:09 UTC, chinmaychinara91 commented
For importing an OBJ into brainstorm:

1. The in_tess_wftobj function in actually a slightly modified submodule of https://www.fieldtriptoolbox.org/reference/fileio/ft_read_headshape. Should we use the fieldtrip function directly or since the license allows us, just continue to do it as it is right now (and just put a reference to the fieldtrip function).
1. We also use the https://www.fieldtriptoolbox.org/reference/forward/ft_convert_units function to determine the units of the vertices based on the shape of the head. This is a good function to have.

Both these functions are available as part of spm12 plugin (/external/fieldtrip) and also the fieldtrip plugin. How do we go about this ?

2024-09-25 20:36 UTC, rcassani commented
In short, it does not makes too much sense to request the user to install FieldTrip as plugin and Load it to perform trivial operations and things that already in the Brainstorm source code. Moreover, not all functions in FieldTrip are available in the compiled version of Brainstorm.

---

> 1. The in_tess_wftobj function in actually a slightly modified submodule of https://www.fieldtriptoolbox.org/reference/fileio/ft_read_headshape. Should we use the fieldtrip function directly or since the license allows us, just continue to do it as it is right now (and just put a reference to the fieldtrip function).

* The waveform .obj files are simple text files that can be parsed quickly, take a look to a Brainstorm function such as [`in_tess_off.m`](https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/io/in_tess_off.m). Do you have any trouble reading this format of file? Do we want to install full FieldTrip for this?



> 2. We also use the https://www.fieldtriptoolbox.org/reference/forward/ft_convert_units function to determine the units of the vertices based on the shape of the head. This is a good function to have.

* Same thing as the point above. Do we want to install full FieldTrip for this?

* A conversion of surface from Brainstorm > FieldTrip > Brainstorm would be needed.

* Choosing the right scaling for distance units is shown in the [Brainstorm tutorials](https://neuroimage.usc.edu/brainstorm/Tutorials/Epileptogenicity#Import_the_contacts_positions). This is done with a function that is already in Brainstorm, [`channel_fixunits`](https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/sensors/channel_fixunits.m)

2024-09-25 20:42 UTC, chinmaychinara91 commented
@rcassani thanks for pointing out the resources. That makes things much simpler now. I don't think we will need FT now.

2024-10-29 17:35 UTC, rcassani reviewed
## Overall 
Code looks good, almost ready to merge.

- Most of the code duplication mentioned in the previous review has been addressed.

- @chinmaychinara91, I have addressed several of the comments in this review. Please take a look to those changes so you can improve future PRs

- @chinmaychinara91, please remove unnecessary changes that make harder to look at the diff (see comments)

- @chinmaychinara91, also improvement in the comments is needed

## Other points
@tmedani and @chinmaychinara91 

- Using caps without landmarks. The code did not allow using caps that did not have defined "landmark markers", I think is a mistake. The automatic labelling is a tool to help avoiding doing tens of clicks, however, if the users decide to do so they should be able to do it. 

- Automatic labelling results. The automatic labelling should be mentioned in the tutorial (and maybe in the GUI) as an experimental tool, is has not been deeply tested, and the found positions are not always great.

- The code has been refactor, so now it can accept more than the "landmark markers" if the user has already acquire them. This greatly improves the automatic labelling.

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/auto_3dscanner.m
> +    capCenters2d = imfindcircles(capImg2d, [minRadius maxRadius]);
Addressed in XXX

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/auto_3dscanner.m
> +    capPoints3d(:,3) = griddata(surface3dscannerUv.u, surface3dscannerUv.v, surface3dscannerUv.Vertices(:,3), capLayoutPts2dU, capLayoutPts2dV);
Addressed in XXX

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/auto_3dscanner.m
> +    capImg2d(:) = griddata(surface3dscannerUv.u(1:end),surface3dscannerUv.v(1:end),grayness,X(:),Y(:),'linear');
Addressed in XXX

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        bst_error(['Please set the first ' num2str(nLandmarkLabels) ' initialization points in order [ ' sprintf('%s ',eegCapLandmarkLabels{:}) ']'], Digitize.Type, 0);
Addressed in XXX

2024-10-29 17:35 UTC, rcassani commented on toolbox/io/import_surfaces.m
> +        end
Addressed in commit XXXX

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        Digitize.Options.Fids = str_split(res{1}, '()[],;"'' ', true); % remove empty
There is no need to have copies of the code to verify the same parameters

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        Digitize.Options.Fids = str_split(res{1}, '()[],;"'' ', true); % remove empty
Addressed in commit: XXXX

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +%% ===== PLOT next point, or remove last or remove selected point =====
Sections are all capitals

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +            end
This part is a copy/paste of the menu generation for  `tree_callbacks` (https://github.com/brainstorm-tools/brainstorm3/blob/60fe915bc485de5f60ef5ed275eb6021f080df96/toolbox/tree/tree_callbacks.m#L2937)

Can you think in a way to reuse the code?
Maintaining this will be very annoying and prone to errors

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        end
Addressed in commit XXX

2024-10-29 17:35 UTC, rcassani commented on toolbox/sensors/panel_digitize.m
It will be needed to apply the changes that were performed in `panel_digitize_2024` into this one

2024-10-29 17:55 UTC, rcassani commented on toolbox/sensors/panel_digitize.m
Changes in `panel_digitize_2024` from before the review (2e1aae8) to my last commit (d8b7b97):
https://github.com/brainstorm-tools/brainstorm3/compare/2e1aae8..d8b7b97#diff-989687fa8cf3c9eaec6f84f35347469e711da0e0ab109bd9a92ab7f7845e92b4

2024-10-29 18:02 UTC, chinmaychinara91 commented
@rcassani thank you for the review. I will work on the comments you gave and get back.

2024-10-29 19:17 UTC, chinmaychinara91 commented on toolbox/io/in_tess.m
> +end
The reason why I only did it for textured surface is because there is a use case i.e. lets says the user starts the digitization through from `File > Digitize > 3D scanner`, and then uses the `Use existing` option, then this unique naming of the surface would help the user to choose the one he wants easily. 

I agree we can drill it down to all other surface types as well but I did not find a use case
<img src="https://github.com/user-attachments/assets/55788f9a-4238-4806-88b7-930705eecd4e" width="300">
.

2024-10-29 19:32 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +            % Add Random 100 points generation button
We can have it. I had given it a thought but then do we really need more then 100 points because this is just for doing the alignment correct ?
If we decide to have it then we should keep a lower/upper bound to avoid any under/over clustering. Let me know what you think.

2024-10-30 15:12 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +    opts = delimitedTextImportOptions('NumVariables', 10);
No it does not. I will convert the parsing logic similar to that in `in_channel_pom.m` to support older versions.

2024-10-30 15:12 UTC, chinmaychinara91 commented on toolbox/sensors/auto_3dscanner.m
> +function varargout = auto_3dscanner(varargin)
`channel_detect_eegcap_auto` name sounds good. Will make the change.

2024-10-30 16:41 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +vertices = channel_fixunits(vertices, 'm', 1, 1);
@rcassani correct me if I am wrong. 

in the `channel_fixunits`, `FileUnits    : String, expected units` is where it is confusing me. Yes the vertices in the file are already in `mm` in the file and we want to convert it to `m` (multiplying the factor of 0.001 does that). So the "expected units" here is `m` correct ?

2024-10-30 18:55 UTC, rcassani commented on defaults/eeg/ICBM152/channel_WearableSensing_DSI_24.mat
> The Generic >10-20 (19) cap layout inside BST has some of the points inside scalp.

And that should no be.

@tmedani, we would need to check all the caps and project the sensors on the respective scalps.

2024-10-30 18:58 UTC, rcassani commented on toolbox/io/in_tess_wftobj.m
> +    opts = delimitedTextImportOptions('NumVariables', 10);
This will be low priority, we can release it only for R2026b or higher

2024-10-30 19:02 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +            % Add Random 100 points generation button
@chinmaychinara91 you could tests to see if more points are actually helpful.

Related to head points, we need to update the tutorial, it mentions that it is good practice to take points in the boney part of the nose and eyebrows, but that is not what it is shown:

https://neuroimage.usc.edu/brainstorm/Tutorials/TutDigitize3dScanner#Collect_the_desired_number_of_head_shape_points

2024-10-30 19:21 UTC, rcassani commented on toolbox/io/in_tess_wftobj.m
> +vertices = channel_fixunits(vertices, 'm', 1, 1);
Yes, they way it is described is confusing, it means expected units in the file that is being read; not the units at the output of the script. Remember that locations in Brainstorm is saved as meters. Also, if you check the code, this `FileUnits` argument is used only for displaying info to the user when confirmation is needed.

2024-10-30 19:39 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +    opts = delimitedTextImportOptions('NumVariables', 10);
Should we just disable the 3DScanner menu option and importing WFTOBJ surface type for < R2016b

2024-10-31 21:20 UTC, chinmaychinara91 commented on defaults/eeg/ICBM152/channel_WearableSensing_DSI_24.mat
As per slack, we will handle it in a separate PR

2024-10-31 21:21 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +            end
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/f1fc564a0fb5f331749fe6263ed8b29e9b5f4a2e

2024-10-31 21:48 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize.m
Addressed in [82831c3](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/82831c3f62c9d35c81cb8e4f3b6d2aee6a35cede)

2024-10-31 21:49 UTC, chinmaychinara91 commented on toolbox/gui/view_surface_matrix.m
> +
Addressed in [a1e2eb1](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/a1e2eb12c4c45709fab05d993df6069ad353ae94)

2024-10-31 21:50 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +    opts = delimitedTextImportOptions('NumVariables', 10);
> Should we just disable the 3DScanner menu option and importing WFTOBJ surface type for < R2016b

Did this here https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/21d0a0932aef2583bfc69a7a24c33d8eb0b01e3b

2024-10-31 21:51 UTC, chinmaychinara91 commented on toolbox/sensors/auto_3dscanner.m
> +function varargout = auto_3dscanner(varargin)
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/7c0680596bddaf1bc9b43f473eb293cacb362da1

2024-10-31 21:51 UTC, chinmaychinara91 commented on toolbox/sensors/auto_3dscanner.m
> +    % create a copy of the input mesh to add UV texture information to it as well
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/81d17908111cb677ebcfe2f183c101dd85aff160 https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/20bc51a157ec19d411c611bcd45f337e30102e34

2024-10-31 21:52 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +            % load the surface
Addressed in https://github.com/brainstorm-tools/brainstorm3/commit/81d17908111cb677ebcfe2f183c101dd85aff160 https://github.com/brainstorm-tools/brainstorm3/commit/20bc51a157ec19d411c611bcd45f337e30102e34

2024-10-31 21:52 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +vertices = channel_fixunits(vertices, 'm', 1, 1);
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/cb0267b4155d98522803341741975c53a3f61734

2024-10-31 21:52 UTC, chinmaychinara91 commented on toolbox/tree/tree_callbacks.m
> +
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/a1e2eb12c4c45709fab05d993df6069ad353ae94

2024-10-31 21:53 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +%% ===== PLOT next point, or remove last or remove selected point =====
Addressed in https://github.com/brainstorm-tools/brainstorm3/commit/81d17908111cb677ebcfe2f183c101dd85aff160 https://github.com/brainstorm-tools/brainstorm3/commit/20bc51a157ec19d411c611bcd45f337e30102e34

2024-11-01 09:04 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +            % Add Random 100 points generation button
@rcassani proceeded with the tutorial recommended way (almost). Check https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/4265a266e57f3eb4f7515642aa31243ced6827c9. This does a pretty decent job in refining. What do you think ?

2024-11-01 20:22 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +            end
This code creates a GUI menu, it does not makes much sense to have them as a subfunction inside `auto_3dscanner`.

Create a new file called `menu_default_eegcaps.m` in `/toolbox/gui/`

`menu_default_eegcaps(jMenu, iAllStudies, isAddLoc)`

For treecallbacks:
`menu_default_eegcaps(jMenu, iAllStudies, isAddLoc)`

For digitizer:
`menu_default_eegcaps(jMenu)`
- Check that the Digitizer panels is open
- Check the digitizer version, to call the correct `AddMontage` function

2024-11-01 20:25 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +        otherwise
Use explicit the case 'Digitize'

2024-11-01 20:27 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +    Digitize.Options.ComPort  = str2double(res{1});
Are you 100% sure of this change? 
Before the PR the parameter was a string, and it has been working without troubles

2024-11-01 20:32 UTC, rcassani commented on toolbox/io/in_tess.m
> +end
Since the comment comes from the filename. To be the same Comment, the user would need to importg textured files with the same filenames, not likely. 

If you want to keep it, extend to all the surfaces types.

P.S. `strcmpi(FileFormat, 'WFTOBJ')` just checks for the format. While we do not support other textured files, we would certainly add more formats.

2024-11-04 01:54 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +    Digitize.Options.ComPort  = str2double(res{1});
My mistake. Mistook `ComPort` for a number. Reverted it back in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/04400ad04fc79350a2ba934dfa67c8dfa71bff1b.

2024-11-04 01:55 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +        otherwise
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/9ab42ab23e0c44b551e1fdb40b6b1954f97ab532

2024-11-04 02:41 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +            end
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/9f2346ccf5821dd97537f4fe1e11ca296ec1d851

2024-11-04 02:55 UTC, chinmaychinara91 commented on toolbox/io/in_tess.m
> +end
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/65b4fbdb4349c2bb52ab3a27d7a47b72f6b82017

2024-11-04 03:13 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
>      % Ask options
I am getting this error here:
![Screenshot 2024-11-03 174826](https://github.com/user-attachments/assets/f391893a-1fb7-4f18-a6c5-531be8b05290)

It just happened randomly. Steps to reproduce:
1. Create a new subject by `File>Digitize>3D scanner`
2. Click `Edit Settings`. Click `OK`. Close the digitizer menu.
3. Click `File>Digitize>Digitizer`.
4. Click `Edit Settings`. Click `OK`. Close the digitizer menu.
5. Repeat steps 1 to 4, around 3-4 times
6. While doing step-4 I get this error. Once I get it then for every other time I try doing step-4 this error persists.

On debugging, I see that the `ComPort` which is set to `COM1` and `UnitType` which is set to `fastrak` as default, just goes empty at end of step-5. @rcassani can you check if it happens at your end as well.

2024-11-04 03:15 UTC, chinmaychinara91 commented on toolbox/sensors/panel_digitize_2024.m
> +    [resType, isCancel] = java_dialog('input', options_all(iOptionsType,1), [Digitize.Type ' configuration'], [], options_all(iOptionsType,2));
I am getting this error here:
![Screenshot 2024-11-03 174826](https://github.com/user-attachments/assets/f391893a-1fb7-4f18-a6c5-531be8b05290)

It just happened randomly. Steps to reproduce:
1. Create a new subject by `File>Digitize>3D scanner`
2. Click `Edit Settings`. Click `OK`. Close the digitizer menu.
3. Click `File>Digitize>Digitizer`.
4. Click `Edit Settings`. Click `OK`. Close the digitizer menu.
5. Repeat steps 1 to 4, around 3-4 times
6. While doing step-4 I get this error. Once I get it then for every other time I try doing step-4 this error persists.

On debugging, I see that the `ComPort` which is set to `COM1` and `UnitType` which is set to `fastrak` as default, just goes empty at end of step-5. @rcassani can you check if it happens at your end as well.

2024-11-04 03:34 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +    opts = delimitedTextImportOptions('NumVariables', 10);
I tried using two methods to test if we can do some obj loading for versions < 2016b:
1. https://www.mathworks.com/matlabcentral/fileexchange/18957-readobj
2. https://www.mathworks.com/matlabcentral/fileexchange/134606-read-obj-files

Method-1 is parsing using line by line parsing considering the obj as a text file using `sscanf` but the problem is it is very very slow. I ran with R2014a and for loading the test obj file we are using it took 40 minutes which is not ideal at all. Most of the scans that users will be using will be around this dense or more.

Method-2 is an optimized way of handling method-1. But still for versions < 2016b it does not work well. I feel the current implementation is already a very good method if we want to keep things >= R2016b.

I have spent significant time on this already. Let me know what your thoughts are on this @rcassani or if you could recommend something better.

2024-11-04 21:49 UTC, rcassani commented on toolbox/gui/gui_brainstorm.m
> +            end
Do not disable this feature because the reader for wavefront `.obj` files is not compatible with versions < R2016b

2024-11-04 21:49 UTC, rcassani commented on toolbox/io/in_tess.m
> +    iSurf = find(cellfun(@(x)~isempty(regexp(x, 'tess_', 'match')), {sSubject.Surface.FileName}));
All the files in `sSubject.Surface.FileName` are surfaces.
There is no need to test if they start with `tess`; just check the comments of the existent surfaces.

2024-11-04 21:49 UTC, rcassani commented on toolbox/io/in_tess_wftobj.m
> +    opts = delimitedTextImportOptions('NumVariables', 10);
> Method-1 is parsing using line by line parsing considering the obj as a text file using sscanf but the problem is it is very very slow.

Parsing line by line is a bad idea:
1. There are 
2. The file is small to be read at once

> Method-2 is an optimized way of handling method-1. But still for versions < 2016b it does not work well as the readtable was not very well developed to handle files as table very well.

@chinmaychinara9, I'll push a snippet on how this can be done
It is a text file, parsing should not be hard

2024-11-04 21:49 UTC, rcassani commented on toolbox/tree/tree_callbacks.m
> +
Remove this limitation

2024-11-04 22:04 UTC, rcassani commented on toolbox/io/in_tess_wftobj.m
> +    textureIdx = elementData{3}; % TODO Select the proper columns
@chinmaychinara91 complete a test the text parsing

2024-11-04 22:07 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +    textureIdx = elementData{3}; % TODO Select the proper columns
Thanks @rcassani will test and get back

2024-11-05 01:02 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +    textureIdx = elementData{3}; % TODO Select the proper columns
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/249961aa496e4a4ac2844dbce2e6c83d3de31f4e

2024-11-05 01:10 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +        elementTmp = cat(1, elementTmp{:});
fails at this line here for this data which came directly from Revopoint scan software: 
https://drive.google.com/file/d/1vYLkujKJX6dsVWxlOtEDeTO_xL0RAqpx/view?usp=sharing 

Error:
```
Error using cat
Dimensions of matrices being concatenated are not consistent.
```

Works well for this data which was cleaned and reexported using MeshLab: https://drive.google.com/file/d/1TyUONrM24NeQukFpkvNDGA-0FaFzgzVz/view?usp=sharing

2024-11-05 01:19 UTC, chinmaychinara91 commented on toolbox/io/in_tess.m
> +    iSurf = find(cellfun(@(x)~isempty(regexp(x, 'tess_', 'match')), {sSubject.Surface.FileName}));
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/b9f2c6f4b3e009e2d3853e5b178dce227d7f0d53

2024-11-05 01:28 UTC, chinmaychinara91 commented on toolbox/tree/tree_callbacks.m
> +
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/3852eeab0caeef1859926f4457e5da59d5b7e38e

2024-11-05 01:28 UTC, chinmaychinara91 commented on toolbox/gui/gui_brainstorm.m
> +            end
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/3852eeab0caeef1859926f4457e5da59d5b7e38e

2024-11-05 01:29 UTC, chinmaychinara91 commented on toolbox/io/in_tess.m
> +    iSurf = find(cellfun(@(x)~isempty(regexp(x, 'tess_', 'match')), {sSubject.Surface.FileName}));
Addressed in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/b9f2c6f4b3e009e2d3853e5b178dce227d7f0d53

2024-11-05 06:09 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +    opts = delimitedTextImportOptions('NumVariables', 10);
> From 40 min to 15 s, not bad a x160 speed up. Although, longer than the `readtable` performance

Indeed. This is a really good implementation @rcassani 💯

2024-11-05 07:11 UTC, chinmaychinara91 commented on toolbox/io/in_tess_wftobj.m
> +        elementTmp = cat(1, elementTmp{:});
> fails at this line 61 here for this data which came directly from Revopoint scan software: https://drive.google.com/file/d/1vYLkujKJX6dsVWxlOtEDeTO_xL0RAqpx/view?usp=sharing
> 
> Error:
> 
> ```
> Error using cat
> Dimensions of matrices being concatenated are not consistent.
> ```


On debugging, for the failed file: While parsing for `vt` and concatenating it, it fails nbecause of this:

```
K>> elementTmp{574982}

ans = 

    '3.50314'    '-05'    '0.763701'
 ```

2024-11-05 16:05 UTC, rcassani commented on toolbox/io/in_tess_wftobj.m
> +        elementTmp = cat(1, elementTmp{:});
Solved in [c8af0d7](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/c8af0d758009e225342708da00ac978364a95b95)

2024-11-05 16:07 UTC, rcassani commented on toolbox/io/in_tess.m
> +    iSurf = find(cellfun(@(x)~isempty(regexp(x, 'tess_', 'match')), {sSubject.Surface.FileName}));
Avoid reinventing the wheel. There are functions in our code base to do these task.
See: [86c3ccf](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/86c3ccf48f9272ee9076be0ee2b0ee7b334f3041)

2024-11-05 16:39 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +    [resType, isCancel] = java_dialog('input', options_all(iOptionsType,1), [Digitize.Type ' configuration'], [], options_all(iOptionsType,2));
Yes, this happens as those settings were cleared and saved in the global variable.
Solved in [366303f](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/366303f23e2d789bb89a73c237323a97dd6cf3c8)

2024-11-05 16:41 UTC, rcassani commented
@chinmaychinara91, @tmedani
It seems this PR is ready.

Please add a warning in the tutorials and in the GUI (e.g. when clicking on the Auto button) that the Auto feature is experimental, and results must be carefully verified.

2024-11-05 19:48 UTC, chinmaychinara91 commented
Did the tests. All look good now. It can be merged.

2024-11-06 07:16 UTC, chinmaychinara91 commented
Tutorials updated. Found some more bugs while doing some tests and fixed them in https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/53f04ca38eab3370a2b707eef5485ed7af60cd44 and https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/bcacbcaea9a71017d82ecb3f112bb3f89c1a59b4. It is good to go now.

2024-11-06 15:27 UTC, rcassani commented on toolbox/sensors/panel_digitize.m
> +    java_dialog('warning', 'This is an experimental feature. Please verify the results carefully.', 'Auto Detect EEG electrodes');
Give an option to cancel the action. 
Currently if the user cancels the window, the auto localization still continues.

2024-11-06 15:29 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +    if strcmpi(Digitize.Type, '3DScanner') && ~strcmpi(Digitize.Points(Digitize.iPoint).Type, 'EXTRA')
Isn't this change also needed in `panel_digitize`?

2024-11-06 15:37 UTC, rcassani commented on toolbox/sensors/panel_digitize.m
> +    java_dialog('warning', 'This is an experimental feature. Please verify the results carefully.', 'Auto Detect EEG electrodes');
You could do:

```
if ~java_dialog('confirm', ....
    return
end
```

2024-11-06 15:56 UTC, rcassani commented on toolbox/sensors/panel_digitize.m
> +    java_dialog('warning', 'This is an experimental feature. Please verify the results carefully.', 'Auto Detect EEG electrodes');
Done at [fb2a8eb](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/fb2a8eb4ffeb452e3ddd6477421897c5f5de4443)

2024-11-06 16:43 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +    if strcmpi(Digitize.Type, '3DScanner') && ~strcmpi(Digitize.Points(Digitize.iPoint).Type, 'EXTRA')
Did you try this? Because this is not how it works. If all the EEG positions are acquired, it will enable the Auto button even when EXTRA points are being acquired as all the required EEG are already there.

2024-11-06 16:43 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +    if strcmpi(Digitize.Type, '3DScanner') && ~strcmpi(Digitize.Points(Digitize.iPoint).Type, 'EXTRA')
Solved in [0e4637d](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/0e4637d4c65ca8fa92d1da4d747a520779888289)

2024-11-06 16:44 UTC, rcassani commented on toolbox/sensors/panel_digitize_2024.m
> +    if strcmpi(Digitize.Type, '3DScanner') && ~strcmpi(Digitize.Points(Digitize.iPoint).Type, 'EXTRA')
In the same part of the code there was this bug: [67e0f8](https://github.com/brainstorm-tools/brainstorm3/pull/716/commits/f67e0f8610b739bf49bdc303b06dbce1147ac73f)

2024-11-06 21:24 UTC, rcassani approved these changes

2024-11-06 23:27 UTC, merged