[Tutorial] EEG and epilepsy - add cMEM estimate
brainstorm-tools/brainstorm3 pull request #721
Opened 2024-07-11 20:30 UTC by Edouard2laire

Hello, 

This add the cMEM estimate in the script of the tutorial. 

Should we move the MEM section (https://neuroimage.usc.edu/brainstorm/Tutorials/Epilepsy#Source_analysis:_MEM_inverse_solution) in Source analysis: Surface  after the sLoreta estimation ?

2024-07-15 16:12 UTC, rcassani commented on toolbox/script/tutorial_epilepsy.m
> +                     'version',     '3.0.0', ...
Version `3.0.0`?
This is not available as plugin yet

2024-07-15 16:17 UTC, Edouard2laire commented on toolbox/script/tutorial_epilepsy.m
> +                     'version',     '3.0.0', ...
i should merge this PR: https://github.com/multifunkim/best-brainstorm/pull/13 this week moving the version to 3.0.0

2024-07-15 16:23 UTC, rcassani commented on toolbox/script/tutorial_epilepsy.m
> +                     'version',     '3.0.0', ...
Perfect, please change this PR to Draft, and back to Read-to-review when its ready

2024-07-15 16:27 UTC, Edouard2laire commented
> When trying to run the pipeline, running:
> 
> `sAvgSrcMEM = bst_process('CallProcess', 'process_inverse_mem', sFilesAvg, [], ...`
> 
> gives the error:
> 
> ```
> Line 16: fminusub
> Objective function is undefined at initial point. Fminunc cannot continue.
> _______________________________________________
> Call stack: 
> >fminusub.m at 16 
> >fminunc.m at 488 
> >be_minimize_free_energy.m at 56 
> >be_solve_mem.m at 56 
> >be_launch_mem.m>MEM_mainLoop at 185 
> >be_launch_mem.m at 79 
> >be_cmem_solver.m at 182 
> >be_main_call.m at 157 
> >be_main.m at 60 
> >process_inverse.m>Compute at 696 
> >process_inverse.m at 24 
> >process_inverse_mem.m>Run at 139 
> >process_inverse_mem.m at 24 
> >bst_process.m>Run at 236 
> >bst_process.m>CallProcess at 2316
> >bst_process.m at 38
> ```
> 


Did you download the new MEM version https://github.com/Edouard2laire/best-brainstorm/archive/refs/heads/wMEM.zip? 

this error is due to the fact that the script is having an error with the forward model
<img width="1353" alt="image" src="https://github.com/user-attachments/assets/0737d669-ad98-4ea3-8df2-fd53fa2ca5d1">

So for some vertex, G is 0 for all the sensors and it cause issue with MEM. 


> > How can i update the MEM figure from the tutorial ? i would like to change it to
> 
> Firs,t login in the in the Brainstorm website, button at upper right corner. (If you do not have an account, please send me an email, so I can give you the necessary info details on creating one)
> 
> After login, on the tutorial page to edit, go to the top navigatin bar, then Menu > Attachments. Then update the tutorial, use this use this syntax:
> 
> {{attachment:sim_ar_spectra_metrics.png||width="100%"}} More info on working with images on Moinmoin here: http://moinmo.in/HelpOnImages

Thx. :)

2024-07-15 16:47 UTC, Edouard2laire commented
also @rcassani, what do you think of the idea to move MEM just after sLoreta ? i think it make more sense to do all the Source analysis: Surface at the same time instead of sLoreta, then volume then back to surface with MEM

2024-07-15 17:21 UTC, rcassani commented
I tried with the `master` branch on https://github.com/Edouard2laire/best-brainstorm which is the one used in Brainstorm when installing and updating the `brainentropy` plugin

About the order, I think we can move MEM after sLORETA. With its own section with the [Advance] label.

2024-07-15 21:20 UTC, Edouard2laire commented
>> About the order, I think we can move MEM after sLORETA. With its own section with the [Advance] label.


ok. if I may, the tutorial editor is probably the worst editor i had to use to write text so far.

2024-07-15 22:10 UTC, rcassani commented
Indeed, writing in MoinMoin is a real pain, apologies for all the suffering.
Few pointers:

* Admin users can revert pages (let me know if you need to do so)
* The slowness things is not on MoinMoin side, but today's issue with the server
* It helps to edit the text without their fancy editor, but using the "Show Raw Text" editor

2024-07-16 01:03 UTC, Edouard2laire commented
Hi @rcassani 

it seems that the change in the BEM surface https://github.com/brainstorm-tools/brainstorm3/pull/721/commits/fcce1d7d10135be1952dc76af09c5d7d40227524 to fix the warning about dipole outside the skull is making quite a difference in the inverse problem solution; including for sLoreta: 

<img width="1080" alt="Screenshot 2024-07-15 at 21 01 26" src="https://github.com/user-attachments/assets/b5b2d0e7-8a9a-4bd6-9a34-1a8f798ac2ac">

Do you know if that is correct ?

2024-07-16 03:37 UTC, Edouard2laire commented
> Indeed, writing in MoinMoin is a real pain, apologies for all the suffering. Few pointers:
> 
> * Admin users can revert pages (let me know if you need to do so)
> * The slowness things is not on MoinMoin side, but today's issue with the server
> * It helps to edit the text without their fancy editor, but using the "Show Raw Text" editor

Indeed, the raw text editor is much better ! :)

2024-07-16 15:01 UTC, rcassani commented on toolbox/script/tutorial_epilepsy.m
> +    'ninner',      1922, ...
This is not a bug, it was decided so the script can run faster and on computers with limited resources

2024-07-24 21:41 UTC, Edouard2laire commented on toolbox/script/tutorial_epilepsy.m
> +    'ninner',      1922, ...
Done.

2024-09-05 18:40 UTC, Edouard2laire commented
https://github.com/multifunkim/best-brainstorm/pull/13 is now merged.  The PR is now ready to be reviewed :)

2024-11-07 20:04 UTC, rcassani requested changes
@Edouard2laire, to avoid duplication of code, and potential problems in maintenance.
I think for the `tutorial_BEst.m` we can use the same approach as in the brain fingerprint tutorial script, where it starts with an already processed Protocol.

* https://neuroimage.usc.edu/brainstorm/Tutorials/BrainFingerprint
* https://github.com/brainstorm-tools/brainstorm3/blob/6c646d2248c877a481dcf1e7308ff5287992a676/toolbox/script/tutorial_brain_fingerprint.m#L63-L68

So `tutorial_BEst.m` will look for the the 'TutorialIntroduction' and do the steps starting with L411:

```
%% ===== TUTORIAL #20: HEAD MODEL ====================================================
%  ===================================================================================
```

2024-11-07 20:04 UTC, rcassani commented on toolbox/script/tutorial_BEst.m
> +    'dcoffset',       0, ...  % Block by block, to avoid effects of slow shifts in data
As identity is required, the `dcoffset` is ignored. However, `dcoffset` is a `radio` option, it's value must be `>=1`.

Set it to `1` so it matches the comment of the same line

2024-11-07 20:04 UTC, rcassani commented on toolbox/script/tutorial_BEst.m
> +%% ===== SAVE REPORT =====
Empty line is needed

2024-11-19 17:24 UTC, rcassani commented on toolbox/script/tutorial_BEst.m
> +% 3. Localizing all scale:
"Devient"

2024-11-21 20:49 UTC, merged