Refactor `SEEG/ECOG Implantation`
brainstorm-tools/brainstorm3 pull request #753
Opened 2024-11-19 21:16 UTC by chinmaychinara91

This PR refactors the **SEEG/ECOG Implantation** option:

1. Users can **right click on a CT or MRI** individually and start implantation. Only show MRI Viewer and load iEEG panel.

2. Users can now **right click on the Subject** both in **Anatomy** and **Functional** modes, and use the GUI above to decide on what modalities they want to proceed with. 
![Screenshot 2024-11-19 125245](https://github.com/user-attachments/assets/810a7a15-c74d-4865-aeae-cf061616a9f2)
-  `MRI`: Start implantation on the default MRI. Only show MRI Viewer and load iEEG panel. This is similar **to right click on a MRI and start implantation**.
- `CT`: Start implantation on the CT. If multiple CTs then UI pops up for users to choose. Only show MRI Viewer and load iEEG panel. This is similar **to right click on a CT and start implantation**.
- `MRI+CT`: Start implantation with CT overlayed on default MRI. If multiple CTs then UI pops up for users to choose. Only show MRI Viewer and load iEEG panel.
- `MRI+CT+Isosurface`: Start implantation with CT overlayed on default MRI. Since there can be only one isosurface per subject as of now, based on which CT file the isosurface was generated from, it loads that CT. If the associated CT is not found then UI pops up for users to choose. Show MRI Viewer, show 3D fig and load iEEG panel.

Special case (@rcassani correct me here if I am wrong):
- `CT+Isosurface`: This is a case when users would just import raw CTs and start their implantation without having an MRI. Results will be same as `MRI+CT+Isosurface` case just that MRI viewer will just have CT and 3D fig will have the isosurface+ct3D.

Relevant forum topics:
- https://neuroimage.usc.edu/forums/t/electrode-location-using-brianstrom-of-verison-25-oct-2024/48747/10

2024-11-20 21:20 UTC, rcassani requested changes
While the PR works, the organization of the code can be greatly improved.

There are GUI interaction in different parts, including plotting, which should not be the case

EDIT: This is the diff for all the changes that I added:
https://github.com/brainstorm-tools/brainstorm3/compare/547a300..17a68e2

2024-11-20 21:23 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +    %
Solved in abfa1caa051ca87ea64d52a93f7c83252c343343

2024-11-20 21:23 UTC, rcassani commented on toolbox/anatomy/tess_isosurface.m
> +    sMesh = bst_history('add', sMesh, 'threshold_ct', ['Thresholded CT: ' sMri.FileName]);
Added in 1df44554574f1d45890cfd42b140a7ca1abf2277

2024-11-20 21:24 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +
Changed in f1b456ad34d778930db6032ceab69eab1ec46a35

2024-11-20 21:25 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +% USAGE:  [hFig, iDS, iFig] = DisplayChannelsMri(ChannelFile, Modality, iAnatomy, isEdit=0, VolMat=struct([]))
Changed in 44eb30fc24dce9587f2b7e2c1a16391ce72eec70

2024-11-20 21:28 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +    end
Changed in 44eb30fc24dce9587f2b7e2c1a16391ce72eec70

```
% == DISPLAY THE MRI VIEWER
    if length(MriFiles) == 1
        [hFig, iDS, iFig] = view_mri(MriFiles{1}, [], [], 2);
    else
        [hFig, iDS, iFig] = view_mri(MriFiles{1}, MriFiles{2}, [], 2);
    end
```

2024-11-20 21:33 UTC, rcassani commented on toolbox/gui/panel_ieeg.m
> +                    iCtFile = find(cellfun(@(x) ~isempty(regexp(x, ctEntry{1}, 'match')), {sSubject.Anatomy.FileName}));
Keep it simple
[~, iCtIso] = ismember(ctEntry{1}, {sSubject.Anatomy.FileName});

Changed: 44eb30fc24dce9587f2b7e2c1a16391ce72eec70

2024-11-22 00:08 UTC, chinmaychinara91 commented on toolbox/gui/panel_ieeg.m
> -                    if ~isempty(iCtIso)
**Issue-1:**
![Screenshot 2024-11-20 151323](https://github.com/user-attachments/assets/9b9a6634-5418-41ff-9e26-f96c2ec9e520)
Steps:
1. Have multiple CTs and no MRI for a subject.
2. Generate isoSurface from one of the CTs and delete the source CT.
3. Start implantation by right clicking on subject. Select `CT+IsoSurf`. Error comes.

**Issue-2:**
Steps:
1. Have MRI and multiple CTs for a subject
2. Generate isoSurface from one of the CTs and delete the source CT.
2. Generate isoSurface from one of the CTs and delete the source CT.
3. Start implantation by right clicking on subject. Select `MRI+CT_IsoSurf`.
**Result:** The MRI viewer opens up with just MRI and 3D figure with isoSurface+3DMRI.

Expected: In both cases the dialog box for **The CT that was used to create the IsoSurface cannot be found.** should pop up.

Fixed in

2024-11-22 00:11 UTC, chinmaychinara91 commented
It looks good now. I ran the tests and it seems good to be merged :).

2024-11-22 16:35 UTC, merged