Refactor skull stripping
brainstorm-tools/brainstorm3 pull request #754
Opened 2024-11-26 02:53 UTC by chinmaychinara91

While importing CT and co-registering using  SPM or CT2MRI, give option for skull stripping either using **BrainSuite (Brain Surface Extractor)** or **SPM (Tissue segmentation)**

![Screenshot 2024-11-25 185212](https://github.com/user-attachments/assets/a461c0c2-29dc-44e7-b5a0-f6075fab2f22)

2024-11-27 20:06 UTC, rcassani requested changes
The PR implements the different methods for skull stripping when coregistering a CT to a MRI volume.

1. As it is skull stripping is inside `mri_coregister` then it only available on importing C, so there are serious limitations:

- It cannot be used on an already imported coregisted CT volume
- It cannot be used if a CT volume is imported and then coregistered from popup menu

The tags are in wrong order, e.g., '...CT_spm_masked_spm_reslice' it implies masked happened before reslicing, which is not the case

2024-11-27 20:06 UTC, rcassani commented on toolbox/anatomy/mri_coregister.m
> +function [sMriMask, MaskTag] = generate_skull_mask(NiiRefFile, TmpDir, MaskMethod)
Masked CT does not have any track of the skull stripping procedure in its history.

2024-11-27 20:06 UTC, rcassani commented on toolbox/anatomy/mri_coregister.m
> +            sMri = in_mri_nii(NiiRefFile, 0, 0, 0);
sMRI converted to `.nii` before the function, then converted back to sMRI. Not very efficient

2024-11-27 20:06 UTC, rcassani commented on toolbox/io/import_mri.m
> +                                                            'This operation cleans the CT to exclude any thing outside the skull.<BR><BR>' ...
Skull-stripping also removes the skull, not only "any thing outside the skull"

2024-11-27 20:07 UTC, rcassani commented on toolbox/anatomy/mri_coregister.m
Fixed in [1dc3dab](https://github.com/brainstorm-tools/brainstorm3/pull/754/commits/1dc3dab4480d54f5b2d422a233a639bba9e49ad7)

2024-11-27 20:08 UTC, rcassani commented on toolbox/anatomy/mri_coregister.m
> +function [sMriMask, MaskTag] = generate_skull_mask(NiiRefFile, TmpDir, MaskMethod)
Done in `mri_skullstrip` in [1dc3dab](https://github.com/brainstorm-tools/brainstorm3/pull/754/commits/1dc3dab4480d54f5b2d422a233a639bba9e49ad7)

2024-11-27 20:09 UTC, rcassani commented on toolbox/io/import_mri.m
> +                                                            'This operation cleans the CT to exclude any thing outside the skull.<BR><BR>' ...
See [915277a](https://github.com/brainstorm-tools/brainstorm3/pull/754/commits/915277a2f3bec4d27ad83a3800839b34d3de5a1e)

2024-11-27 22:31 UTC, chinmaychinara91 commented on toolbox/anatomy/mri_skullstrip.m
> +function [MriFileMask, errMsg, fileTag, binBrainMask] = mri_skullstrip(MriFileSrc, MriFileRef, Method)
@rcassani Should we also add the `sMriMask` structure ? While it might be ambiguous since users can use the output `MriFileMask` with `bst_memory(LoadMri)` to load it if they want but I was just comparing it with `mri_reslice` and thinking if we should.

2024-11-27 23:01 UTC, rcassani commented on toolbox/anatomy/mri_skullstrip.m
> +function [MriFileMask, errMsg, fileTag, binBrainMask] = mri_skullstrip(MriFileSrc, MriFileRef, Method)
I would say that there is no value in adding `sMriMask` as output argument. If the user is working with structures, this output argument will be repeated. There is not point in adding it.

> I was just comparing it with mri_reslice and thinking if we should.

Did you find a use for that output argument? 
That `mri_reslice` has it is not a good enough reason to add it.

2024-11-27 23:04 UTC, chinmaychinara91 commented on toolbox/anatomy/mri_skullstrip.m
> +function [MriFileMask, errMsg, fileTag, binBrainMask] = mri_skullstrip(MriFileSrc, MriFileRef, Method)
> Did you find a use for that output argument?

No I did not. I think it is ambiguous.

2024-11-27 23:19 UTC, rcassani commented on toolbox/anatomy/mri_skullstrip.m
> +function [MriFileMask, errMsg, fileTag, binBrainMask] = mri_skullstrip(MriFileSrc, MriFileRef, Method)
What do you mean with ambiguous? 

The same happens with the input arguments they can be either structures or filenames.
You can see it a way to function overloading

2024-11-28 12:44 UTC, rcassani commented on toolbox/anatomy/mri_skullstrip.m
I appreciate your enthusiasm, in expanding the help for the function.

However, I think the USAGE was clear, it shows that the if the function has as input filesnames for files in the DB e.g., `MriFileSrc` it returns a filename `MriFileMask` which implies is already register in the DB. If the inputs are structures `sMriSrc` (with the start `s` as we do it in the code and mentioned in the naming conventions), the result is a  structure `sMriMask`.

Moreover, the added descriptions has troubles:
1. It does not mention that the inputs can be structures
2. It misleads saying that the input paths are relative, they can also be absolutes
3. It does not mention that the output can be structure

2024-11-28 18:15 UTC, rcassani approved these changes

2024-11-28 18:20 UTC, merged